Shader "Hidden/LineShader" {
	Properties {
	}
	SubShader {
		Pass {
			Blend SrcAlpha OneMinusSrcAlpha, SrcAlpha OneMinusSrcAlpha
			ZWrite Off
			Cull Off
			Fog {
				Mode Off
			}
			GpuProgramID 31385
			Program "vp" {
				SubProgram "d3d11 " {
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// TEXCOORD                 0   xy          0     NONE   float   xy  
					// POSITION                 0   xyzw        1     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// TEXCOORD                 0   xy          0     NONE   float   xy  
					// SV_Position              0   xyzw        1      POS   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[21], immediateIndexed
					dcl_input v0.xy
					dcl_input v1.xyz
					dcl_output o0.xy
					dcl_output_siv o1.xyzw, position
					dcl_temps 2
					mov o0.xy, v0.xyxx
					mul r0.xyzw, v1.yyyy, cb0[1].xyzw
					mad r0.xyzw, cb0[0].xyzw, v1.xxxx, r0.xyzw
					mad r0.xyzw, cb0[2].xyzw, v1.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb0[3].xyzw
					mul r1.xyzw, r0.yyyy, cb1[18].xyzw
					mad r1.xyzw, cb1[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb1[19].xyzw, r0.zzzz, r1.xyzw
					mad o1.xyzw, cb1[20].xyzw, r0.wwww, r1.xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// TEXCOORD                 0   xy          0     NONE   float   xy  
					// SV_Position              0   xyzw        1      POS   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[1], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v0.xy
					dcl_output o0.xyzw
					dcl_temps 1
					sample r0.xyzw, v0.xyxx, t0.xyzw, s0
					mul o0.xyzw, r0.xyzw, cb0[0].xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
}