Shader "Hidden/BlurEffectConeTap" {
	Properties {
		_MainTex ("", any) = "" {}
	}
	SubShader {
		Pass {
			ZTest Always
			ZWrite Off
			Cull Off
			GpuProgramID 50904
			Program "vp" {
				SubProgram "d3d11 " {
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1   xy          2     NONE   float   xy  
					// TEXCOORD                 2   xy          3     NONE   float   xy  
					// TEXCOORD                 3   xy          4     NONE   float   xy  
					// TEXCOORD                 4   xy          5     NONE   float   xy  
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_output o2.xy
					dcl_output o3.xy
					dcl_output o4.xy
					dcl_output o5.xy
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mad r0.xy, -cb0[3].xyxx, cb0[2].xyxx, v1.xyxx
					mov o1.xy, r0.xyxx
					mov o2.xy, v1.xyxx
					mad o3.xy, -cb0[3].xyxx, cb0[2].xyxx, r0.xyxx
					mul r0.zw, cb0[2].xxxy, cb0[3].xxxy
					mad o4.xy, r0.zwzz, l(1.000000, -1.000000, 0.000000, 0.000000), r0.xyxx
					mad o5.xy, -r0.zwzz, l(1.000000, -1.000000, 0.000000, 0.000000), r0.xyxx
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float       
					// TEXCOORD                 1   xy          2     NONE   float   xy  
					// TEXCOORD                 2   xy          3     NONE   float   xy  
					// TEXCOORD                 3   xy          4     NONE   float   xy  
					// TEXCOORD                 4   xy          5     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v2.xy
					dcl_input_ps linear v3.xy
					dcl_input_ps linear v4.xy
					dcl_input_ps linear v5.xy
					dcl_output o0.xyzw
					dcl_temps 2
					sample r0.xyzw, v2.xyxx, t0.xyzw, s0
					sample r1.xyzw, v3.xyxx, t0.xyzw, s0
					add r0.xyzw, r0.xyzw, r1.xyzw
					sample r1.xyzw, v4.xyxx, t0.xyzw, s0
					add r0.xyzw, r0.xyzw, r1.xyzw
					sample r1.xyzw, v5.xyxx, t0.xyzw, s0
					add r0.xyzw, r0.xyzw, r1.xyzw
					mul o0.xyzw, r0.xyzw, l(0.250000, 0.250000, 0.250000, 0.250000)
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
}