Shader "Klei/Building Place" {
	Properties {
		_MainTex ("Tex0", 2D) = "" {}
		_OverlayTex ("Overlay Tex", 2D) = "white" {}
		_StatusColor ("Status Color", Vector) = (0,0,0,0)
		_TintColor ("Tint Color", Vector) = (1,1,1,1)
		_LuminanceFlicker ("Luminance Flicker", Float) = 0.6
		_BarScale ("Bar Scale", Float) = 0.1
	}
	SubShader {
		Tags { "IGNOREPROJECTOR" = "true" "PreviewType" = "Plane" "QUEUE" = "Transparent+500" "RenderType" = "Transparent" }
		Pass {
			Tags { "IGNOREPROJECTOR" = "true" "PreviewType" = "Plane" "QUEUE" = "Transparent+500" "RenderType" = "Transparent" }
			Blend SrcAlpha OneMinusSrcAlpha, SrcAlpha OneMinusSrcAlpha
			ZTest Always
			ZWrite Off
			Cull Off
			GpuProgramID 57343
			Program "vp" {
				SubProgram "d3d11 " {
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1   xy          2     NONE   float   xy  
					// TEXCOORD                 3   xy          3     NONE   float   xy  
					// COLOR                    0   xyzw        4     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 1   xy          2     NONE   float   xy  
					// TEXCOORD                 3     zw        2     NONE   float     zw
					// TEXCOORD                 2   xyz         3     NONE   float   xyz 
					// COLOR                    0   xyzw        4     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[18], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xy
					dcl_input v2.xy
					dcl_input v3.xy
					dcl_input v4.xyzw
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xy
					dcl_output o2.zw
					dcl_output o3.xyz
					dcl_output o4.xyzw
					dcl_temps 2
					mul r0.xy, v0.yyyy, cb0[15].xyxx
					mad r0.xy, cb0[14].xyxx, v0.xxxx, r0.xyxx
					mad r0.xy, cb0[16].xyxx, v0.zzzz, r0.xyxx
					mad r0.xy, cb0[17].xyxx, v0.wwww, r0.xyxx
					mul r1.xyzw, r0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, r0.xxxx, r1.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mul o1.zw, r0.xxxy, cb0[5].zzzw
					mov o3.xyz, r0.xyzx
					mov o1.xy, v1.xyxx
					mov o2.xy, v2.xyxx
					mov o2.zw, v3.xxxy
					mov o4.xyzw, v4.xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 1   xy          2     NONE   float    y  
					// TEXCOORD                 3     zw        2     NONE   float       
					// TEXCOORD                 2   xyz         3     NONE   float       
					// COLOR                    0   xyzw        4     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					// SV_Target                1   xyzw        1   TARGET   float   xyzw
					// SV_Target                2   xyzw        2   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[14], immediateIndexed
					dcl_constantbuffer CB1[1], immediateIndexed
					dcl_constantbuffer CB2[4], immediateIndexed
					dcl_constantbuffer CB3[21], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_sampler s2, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_resource_texture2d (float,float,float,float) t2
					dcl_input_ps linear v1.xyzw
					dcl_input_ps linear v2.y
					dcl_input_ps linear v4.xyzw
					dcl_output o0.xyzw
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_temps 4
					mul r0.xy, v1.zwzz, cb0[5].xyxx
					mul r1.xyzw, r0.yyyy, cb2[1].xyzw
					mad r1.xyzw, cb2[0].xyzw, r0.xxxx, r1.xyzw
					add r1.xyzw, r1.xyzw, cb2[3].xyzw
					mul r0.zw, r1.yyyy, cb3[18].xxxy
					mad r0.zw, cb3[17].xxxy, r1.xxxx, r0.zzzw
					mad r0.zw, cb3[19].xxxy, r1.zzzz, r0.zzzw
					mad r0.zw, cb3[20].xxxy, r1.wwww, r0.zzzw
					mad r0.zw, r0.zzzw, l(0.000000, 0.000000, 0.500000, -0.500000), l(0.000000, 0.000000, 0.500000, 0.500000)
					sample r1.xyzw, r0.zwzz, t1.xyzw, s0
					dp3 r0.z, r1.xyzx, l(0.300000, 0.590000, 0.110000, 0.000000)
					sample r1.xyzw, v1.xyxx, t0.xyzw, s1
					mul r1.xyzw, r1.xyzw, cb0[11].xyzw
					mad r2.xyz, cb0[9].xyzx, cb0[9].wwww, r1.xyzx
					mul r3.xyz, cb0[1].xxxx, cb0[10].xyzx
					mad r1.xyz, r3.xyzx, l(1.500000, 1.500000, 1.500000, 0.000000), r2.xyzx
					mul r1.xyzw, r1.xyzw, v4.xyzw
					mul r2.xyz, r1.xyzx, r1.xyzx
					mul r2.xyz, r2.xyzx, cb0[12].xyzx
					mad r3.xyz, r1.xyzx, r1.xyzx, -r2.xyzx
					mad r2.xyz, r0.zzzz, r3.xyzx, r2.xyzx
					sqrt r1.xyz, r2.xyzx
					mul r2.xyz, cb1[0].xxyx, l(0.000000, 1.000000, 11.000000, 0.000000)
					mad r0.xy, r0.xyxx, cb0[13].xxxx, r2.xyxx
					sincos r0.z, null, r2.z
					sample r2.xyzw, r0.xyxx, t2.xyzw, s2
					mul r1.xyzw, r1.xyzw, r2.xyzw
					add r0.xy, cb1[0].yyyy, l(0.200000, 0.400000, 0.000000, 0.000000)
					mul r0.xy, r0.xyxx, l(37.000000, 5.000000, 0.000000, 0.000000)
					sincos r0.xy, null, r0.xyxx
					mul r0.x, r0.x, r0.z
					mul r0.x, r0.y, r0.x
					max r0.x, r0.x, l(0.000000)
					mad r0.x, -cb0[13].y, r0.x, l(1.000000)
					mad r0.y, r1.w, r0.x, l(-0.007000)
					mul r0.x, r0.x, r1.w
					mov o0.xyz, r1.xyzx
					lt r0.y, r0.y, l(0.000000)
					discard_nz r0.y
					mov o0.w, r0.x
					lt r0.x, l(0.750000), r0.x
					mov r1.xzw, l(0,0,0,1.000000)
					mov r1.y, v2.y
					and o1.xyzw, r0.xxxx, r1.xyzw
					mov o2.xyzw, l(0,0,0,0)
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
}