Shader "Klei/Stars " {
	Properties {
		_Tex0 ("Tex0 (RGB)", 2D) = "white" {}
		_Tex1 ("Tex1 (RGB)", 2D) = "white" {}
		_Tex2 ("Tex2 (RGB)", 2D) = "white" {}
		_TexDay0 ("TexDay0 (RGB)", 2D) = "white" {}
		_TexDay1 ("TeDayx1 (RGB)", 2D) = "white" {}
		_TexDay2 ("TexDay2 (RGB)", 2D) = "white" {}
		_Parallax0 ("Parallax 0", Float) = 1.025
		_Parallax1 ("Parallax 1", Float) = 1.1
		_Tint0 ("Tint0", Vector) = (1,1,1,1)
		_Tint1 ("Tint1", Vector) = (1,1,1,1)
		_Tint2 ("Tint1", Vector) = (1,1,1,1)
		_TimeOfDayOverride ("Time Of Day Override", Range(-1, 1)) = -1
		_TimeOfDayMultiplier ("Time Of Day Multiplier", Float) = 1
	}
	SubShader {
		Tags { "IGNOREPROJECTOR" = "true" "PreviewType" = "Plane" "QUEUE" = "Geometry" "RenderType" = "Opaque" }
		Pass {
			Tags { "IGNOREPROJECTOR" = "true" "PreviewType" = "Plane" "QUEUE" = "Geometry" "RenderType" = "Opaque" }
			ZWrite Off
			GpuProgramID 36560
			Program "vp" {
				SubProgram "d3d11 " {
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// TEXCOORD                 0   xy          1     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Position              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 2   xy          2     NONE   float   xy  
					//
					vs_4_0
					dcl_constantbuffer CB0[14], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_constantbuffer CB2[4], immediateIndexed
					dcl_constantbuffer CB3[21], immediateIndexed
					dcl_input v0.xyz
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xy
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb2[1].xyzw
					mad r0.xyzw, cb2[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb2[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb2[3].xyzw
					mul r1.xyzw, r0.yyyy, cb3[18].xyzw
					mad r1.xyzw, cb3[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb3[19].xyzw, r0.zzzz, r1.xyzw
					mad r0.xyzw, cb3[20].xyzw, r0.wwww, r1.xyzw
					mov o0.xyzw, r0.xyzw
					add r0.xy, r0.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
					div r0.w, cb1[6].y, cb1[6].x
					mul r0.w, r0.w, l(1.500000)
					mul r0.z, r0.w, r0.y
					mul r0.xy, r0.xzxx, l(0.750000, 0.500000, 0.000000, 0.000000)
					mul r1.xy, cb0[6].zwzz, cb1[4].xyxx
					mov r1.z, -r1.y
					mad o1.xy, r1.xzxx, cb0[13].xxxx, r0.xyxx
					mad o1.zw, r1.xxxz, cb0[13].yyyy, r0.xxxy
					mov o2.xy, r0.xyxx
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Position              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 2   xy          2     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[14], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_sampler s2, mode_default
					dcl_sampler s3, mode_default
					dcl_sampler s4, mode_default
					dcl_sampler s5, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_resource_texture2d (float,float,float,float) t2
					dcl_resource_texture2d (float,float,float,float) t3
					dcl_resource_texture2d (float,float,float,float) t4
					dcl_resource_texture2d (float,float,float,float) t5
					dcl_input_ps linear v1.xyzw
					dcl_input_ps linear v2.xy
					dcl_output o0.xyzw
					dcl_temps 3
					sample r0.xyzw, v2.xyxx, t1.xyzw, s3
					sample r1.xyzw, v2.xyxx, t0.xyzw, s0
					add r0.xyz, r0.xyzx, -r1.xyzx
					ge r0.w, cb0[13].z, l(0.000000)
					mul_sat r1.w, cb0[9].y, cb0[13].w
					movc r0.w, r0.w, cb0[13].z, r1.w
					mad r0.xyz, r0.wwww, r0.xyzx, r1.xyzx
					mul r0.xyz, r0.xyzx, cb0[10].xyzx
					sample r1.xyzw, v1.xyxx, t3.xyzw, s4
					sample r2.xyzw, v1.xyxx, t2.xyzw, s1
					add r1.xyzw, r1.xyzw, -r2.xyzw
					mad r1.xyzw, r0.wwww, r1.xyzw, r2.xyzw
					mul r2.xyzw, r1.xyzw, cb0[11].xyzw
					mad r1.x, -r1.w, cb0[11].w, l(1.000000)
					mul r1.yzw, r2.wwww, r2.xxyz
					mad r0.xyz, r0.xyzx, r1.xxxx, r1.yzwy
					sample r1.xyzw, v1.zwzz, t5.xyzw, s5
					sample r2.xyzw, v1.zwzz, t4.xyzw, s2
					add r1.xyzw, r1.xyzw, -r2.xyzw
					mad r1.xyzw, r0.wwww, r1.xyzw, r2.xyzw
					mul r2.xyzw, r1.xyzw, cb0[12].xyzw
					mad r0.w, -r1.w, cb0[12].w, l(1.000000)
					mul r1.xyz, r2.wwww, r2.xyzx
					mad o0.xyz, r0.xyzx, r0.wwww, r1.xyzx
					mov o0.w, l(1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
}