Shader "Klei/PostFX/Blur" {
	Properties {
		_MainTex ("Base (RGB)", 2D) = "white" {}
	}
	SubShader {
		Pass {
			GpuProgramID 34704
			Program "vp" {
				SubProgram "d3d11 " {
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Position              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[7], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_output o2.xyzw
					dcl_output o3.xyzw
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mov o1.xy, v1.xyxx
					div r0.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000), cb0[6].xyxy
					mad o2.xy, r0.xyxx, l(1.407333, 1.407333, 0.000000, 0.000000), v1.xyxx
					mad o2.zw, -r0.xxxy, l(0.000000, 0.000000, 1.407333, 1.407333), v1.xxxy
					mad o3.xy, r0.zwzz, l(3.294215, 3.294215, 0.000000, 0.000000), v1.xyxx
					mad o3.zw, -r0.zzzw, l(0.000000, 0.000000, 3.294215, 3.294215), v1.xxxy
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Position              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xy
					dcl_input_ps linear v2.xyzw
					dcl_input_ps linear v3.xyzw
					dcl_output o0.xyzw
					dcl_temps 2
					sample r0.xyzw, v2.xyxx, t0.xyzw, s0
					mul r0.xyz, r0.xyzx, l(0.316216, 0.316216, 0.316216, 0.000000)
					sample r1.xyzw, v1.xyxx, t0.xyzw, s0
					mad r0.xyz, r1.xyzx, l(0.227027, 0.227027, 0.227027, 0.000000), r0.xyzx
					sample r1.xyzw, v2.zwzz, t0.xyzw, s0
					mad r0.xyz, r1.xyzx, l(0.316216, 0.316216, 0.316216, 0.000000), r0.xyzx
					sample r1.xyzw, v3.xyxx, t0.xyzw, s0
					mad r0.xyz, r1.xyzx, l(0.070270, 0.070270, 0.070270, 0.000000), r0.xyzx
					sample r1.xyzw, v3.zwzz, t0.xyzw, s0
					mad o0.xyz, r1.xyzx, l(0.070270, 0.070270, 0.070270, 0.000000), r0.xyzx
					mov o0.w, l(1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
}