Shader "TextMeshPro/Mobile/Distance Field (Surface)" {
	Properties {
		_FaceTex ("Fill Texture", 2D) = "white" {}
		_FaceColor ("Fill Color", Vector) = (1,1,1,1)
		_FaceDilate ("Face Dilate", Range(-1, 1)) = 0
		_OutlineColor ("Outline Color", Vector) = (0,0,0,1)
		_OutlineTex ("Outline Texture", 2D) = "white" {}
		_OutlineWidth ("Outline Thickness", Range(0, 1)) = 0
		_OutlineSoftness ("Outline Softness", Range(0, 1)) = 0
		_GlowColor ("Color", Vector) = (0,1,0,0.5)
		_GlowOffset ("Offset", Range(-1, 1)) = 0
		_GlowInner ("Inner", Range(0, 1)) = 0.05
		_GlowOuter ("Outer", Range(0, 1)) = 0.05
		_GlowPower ("Falloff", Range(1, 0)) = 0.75
		_WeightNormal ("Weight Normal", Float) = 0
		_WeightBold ("Weight Bold", Float) = 0.5
		_ShaderFlags ("Flags", Float) = 0
		_ScaleRatioA ("Scale RatioA", Float) = 1
		_ScaleRatioB ("Scale RatioB", Float) = 1
		_ScaleRatioC ("Scale RatioC", Float) = 1
		_MainTex ("Font Atlas", 2D) = "white" {}
		_TextureWidth ("Texture Width", Float) = 512
		_TextureHeight ("Texture Height", Float) = 512
		_GradientScale ("Gradient Scale", Float) = 5
		_ScaleX ("Scale X", Float) = 1
		_ScaleY ("Scale Y", Float) = 1
		_PerspectiveFilter ("Perspective Correction", Range(0, 1)) = 0.875
		_VertexOffsetX ("Vertex OffsetX", Float) = 0
		_VertexOffsetY ("Vertex OffsetY", Float) = 0
	}
	SubShader {
		LOD 300
		Tags { "IGNOREPROJECTOR" = "true" "QUEUE" = "Transparent" "RenderType" = "Transparent" }
		Pass {
			Name "FORWARD"
			LOD 300
			Tags { "IGNOREPROJECTOR" = "true" "LIGHTMODE" = "FORWARDBASE" "QUEUE" = "Transparent" "RenderType" = "Transparent" }
			Blend SrcAlpha OneMinusSrcAlpha, SrcAlpha OneMinusSrcAlpha
			ColorMask RGB -1
			ZWrite Off
			Cull Off
			GpuProgramID 3709
			Program "vp" {
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// TANGENT                  0   xyzw        1     NONE   float   xyzw
					// NORMAL                   0   xyz         2     NONE   float   xyz 
					// TEXCOORD                 0   xyzw        3     NONE   float   xy  
					// TEXCOORD                 1   xyzw        4     NONE   float   xy  
					// TEXCOORD                 2   xyzw        5     NONE   float       
					// TEXCOORD                 3   xyzw        6     NONE   float       
					// COLOR                    0   xyzw        7     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 1   xy          2     NONE   float   xy  
					// TEXCOORD                 5     zw        2     NONE   float     zw
					// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
					// TEXCOORD                 3   xyzw        4     NONE   float   xyzw
					// TEXCOORD                 4   xyzw        5     NONE   float   xyzw
					// COLOR                    0   xyzw        6     NONE   float   xyzw
					// TEXCOORD                 6   xyz         7     NONE   float   xyz 
					// TEXCOORD                 7   xyz         8     NONE   float   xyz 
					//
					vs_4_0
					dcl_constantbuffer CB0[35], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_constantbuffer CB2[46], immediateIndexed
					dcl_constantbuffer CB3[10], immediateIndexed
					dcl_constantbuffer CB4[21], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xyzw
					dcl_input v2.xyz
					dcl_input v3.xy
					dcl_input v4.xy
					dcl_input v7.xyzw
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xy
					dcl_output o2.zw
					dcl_output o3.xyzw
					dcl_output o4.xyzw
					dcl_output o5.xyzw
					dcl_output o6.xyzw
					dcl_output o7.xyz
					dcl_output o8.xyz
					dcl_temps 5
					add r0.xy, v0.xyxx, cb0[25].zwzz
					mul r1.xyzw, r0.yyyy, cb3[1].xyzw
					mad r1.xyzw, cb3[0].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb3[2].xyzw, v0.zzzz, r1.xyzw
					add r2.xyzw, r1.xyzw, cb3[3].xyzw
					mad r1.xyz, cb3[3].xyzx, v0.wwww, r1.xyzx
					mul r3.xyzw, r2.yyyy, cb4[18].xyzw
					mad r3.xyzw, cb4[17].xyzw, r2.xxxx, r3.xyzw
					mad r3.xyzw, cb4[19].xyzw, r2.zzzz, r3.xyzw
					mad o0.xyzw, cb4[20].xyzw, r2.wwww, r3.xyzw
					mul r0.w, v4.x, l(0.000244)
					round_ni r3.x, r0.w
					mad r3.y, -r3.x, l(4096.000000), v4.x
					mul r3.xy, r3.xyxx, l(0.001953, 0.001953, 0.000000, 0.000000)
					mad o1.zw, r3.xxxy, cb0[33].xxxy, cb0[33].zzzw
					mad o2.xy, r3.xyxx, cb0[34].xyxx, cb0[34].zwzz
					mad o1.xy, v3.xyxx, cb0[32].xyxx, cb0[32].zwzz
					ge r0.w, l(0.000000), v4.y
					and r0.w, r0.w, l(0x3f800000)
					add r1.w, -cb0[24].y, cb0[24].z
					mad r0.w, r0.w, r1.w, cb0[24].y
					mad r0.w, r0.w, l(0.250000), cb0[6].x
					mul r0.w, r0.w, cb0[24].w
					mul o2.z, r0.w, l(0.500000)
					mul r0.w, r2.y, cb4[18].w
					mad r0.w, cb4[17].w, r2.x, r0.w
					mad r0.w, cb4[19].w, r2.z, r0.w
					mad r0.w, cb4[20].w, r2.w, r0.w
					mul r2.xy, cb1[6].yyyy, cb4[6].xyxx
					mad r2.xy, cb4[5].xyxx, cb1[6].xxxx, r2.xyxx
					mul r2.xy, r2.xyxx, cb0[30].yzyy
					div r2.xy, r0.wwww, r2.xyxx
					dp2 r0.w, r2.xyxx, r2.xyxx
					rsq r0.w, r0.w
					mul r1.w, |v4.y|, cb0[30].x
					mul r0.w, r0.w, r1.w
					mul r1.w, r0.w, l(1.500000)
					add r2.x, -cb0[30].w, l(1.000000)
					mul r1.w, r1.w, r2.x
					mad r0.w, r0.w, l(1.500000), -r1.w
					mul r2.xyz, cb1[4].yyyy, cb3[5].xyzx
					mad r2.xyz, cb3[4].xyzx, cb1[4].xxxx, r2.xyzx
					mad r2.xyz, cb3[6].xyzx, cb1[4].zzzz, r2.xyzx
					add r2.xyz, r2.xyzx, cb3[7].xyzx
					mov r0.z, v0.z
					add r0.xyz, -r0.xyzx, r2.xyzx
					dp3 r0.x, v2.xyzx, r0.xyzx
					lt r0.y, l(0.000000), r0.x
					lt r0.x, r0.x, l(0.000000)
					iadd r0.x, -r0.y, r0.x
					itof r0.x, r0.x
					mul r0.xyz, r0.xxxx, v2.xyzx
					dp3 r2.x, r0.xyzx, cb3[4].xyzx
					dp3 r2.y, r0.xyzx, cb3[5].xyzx
					dp3 r2.z, r0.xyzx, cb3[6].xyzx
					dp3 r0.x, r2.xyzx, r2.xyzx
					rsq r0.x, r0.x
					mul r2.xyzw, r0.xxxx, r2.xyzz
					add r0.xyz, -r1.xyzx, cb1[4].xyzx
					dp3 r3.x, r0.xyzx, r0.xyzx
					rsq r3.x, r3.x
					mul r3.xyz, r0.xyzx, r3.xxxx
					dp3 r3.x, r2.xywx, r3.xyzx
					mad o2.w, |r3.x|, r0.w, r1.w
					mov o3.w, r1.x
					mul r3.xyz, v1.yyyy, cb3[1].yzxy
					mad r3.xyz, cb3[0].yzxy, v1.xxxx, r3.xyzx
					mad r3.xyz, cb3[2].yzxy, v1.zzzz, r3.xyzx
					dp3 r0.w, r3.xyzx, r3.xyzx
					rsq r0.w, r0.w
					mul r3.xyz, r0.wwww, r3.xyzx
					mul r4.xyz, r2.wxyw, r3.xyzx
					mad r4.xyz, r2.ywxy, r3.yzxy, -r4.xyzx
					mul r0.w, v1.w, cb3[9].w
					mul r4.xyz, r0.wwww, r4.xyzx
					mov o3.y, r4.x
					mov o3.z, r2.x
					mov o3.x, r3.z
					mov o4.x, r3.x
					mov o5.x, r3.y
					mov o4.w, r1.y
					mov o5.w, r1.z
					mov o4.z, r2.y
					mov o4.y, r4.y
					mov o5.y, r4.z
					mov o5.z, r2.w
					mov o6.xyzw, v7.xyzw
					mul r1.xyz, r0.yyyy, cb0[14].xyzx
					mad r0.xyw, cb0[13].xyxz, r0.xxxx, r1.xyxz
					mad o7.xyz, cb0[15].xyzx, r0.zzzz, r0.xywx
					mul r0.x, r2.y, r2.y
					mad r0.x, r2.x, r2.x, -r0.x
					mul r1.xyzw, r2.ywzx, r2.xyzw
					dp4 r2.x, cb2[42].xyzw, r1.xyzw
					dp4 r2.y, cb2[43].xyzw, r1.xyzw
					dp4 r2.z, cb2[44].xyzw, r1.xyzw
					mad o8.xyz, cb2[45].xyzx, r0.xxxx, r2.xyzx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" "LIGHTPROBE_SH" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// TANGENT                  0   xyzw        1     NONE   float   xyzw
					// NORMAL                   0   xyz         2     NONE   float   xyz 
					// TEXCOORD                 0   xyzw        3     NONE   float   xy  
					// TEXCOORD                 1   xyzw        4     NONE   float   xy  
					// TEXCOORD                 2   xyzw        5     NONE   float       
					// TEXCOORD                 3   xyzw        6     NONE   float       
					// COLOR                    0   xyzw        7     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 1   xy          2     NONE   float   xy  
					// TEXCOORD                 5     zw        2     NONE   float     zw
					// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
					// TEXCOORD                 3   xyzw        4     NONE   float   xyzw
					// TEXCOORD                 4   xyzw        5     NONE   float   xyzw
					// COLOR                    0   xyzw        6     NONE   float   xyzw
					// TEXCOORD                 6   xyz         7     NONE   float   xyz 
					// TEXCOORD                 7   xyz         8     NONE   float   xyz 
					//
					vs_4_0
					dcl_constantbuffer CB0[35], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_constantbuffer CB2[46], immediateIndexed
					dcl_constantbuffer CB3[10], immediateIndexed
					dcl_constantbuffer CB4[21], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xyzw
					dcl_input v2.xyz
					dcl_input v3.xy
					dcl_input v4.xy
					dcl_input v7.xyzw
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xy
					dcl_output o2.zw
					dcl_output o3.xyzw
					dcl_output o4.xyzw
					dcl_output o5.xyzw
					dcl_output o6.xyzw
					dcl_output o7.xyz
					dcl_output o8.xyz
					dcl_temps 5
					add r0.xy, v0.xyxx, cb0[25].zwzz
					mul r1.xyzw, r0.yyyy, cb3[1].xyzw
					mad r1.xyzw, cb3[0].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb3[2].xyzw, v0.zzzz, r1.xyzw
					add r2.xyzw, r1.xyzw, cb3[3].xyzw
					mad r1.xyz, cb3[3].xyzx, v0.wwww, r1.xyzx
					mul r3.xyzw, r2.yyyy, cb4[18].xyzw
					mad r3.xyzw, cb4[17].xyzw, r2.xxxx, r3.xyzw
					mad r3.xyzw, cb4[19].xyzw, r2.zzzz, r3.xyzw
					mad o0.xyzw, cb4[20].xyzw, r2.wwww, r3.xyzw
					mul r0.w, v4.x, l(0.000244)
					round_ni r3.x, r0.w
					mad r3.y, -r3.x, l(4096.000000), v4.x
					mul r3.xy, r3.xyxx, l(0.001953, 0.001953, 0.000000, 0.000000)
					mad o1.zw, r3.xxxy, cb0[33].xxxy, cb0[33].zzzw
					mad o2.xy, r3.xyxx, cb0[34].xyxx, cb0[34].zwzz
					mad o1.xy, v3.xyxx, cb0[32].xyxx, cb0[32].zwzz
					ge r0.w, l(0.000000), v4.y
					and r0.w, r0.w, l(0x3f800000)
					add r1.w, -cb0[24].y, cb0[24].z
					mad r0.w, r0.w, r1.w, cb0[24].y
					mad r0.w, r0.w, l(0.250000), cb0[6].x
					mul r0.w, r0.w, cb0[24].w
					mul o2.z, r0.w, l(0.500000)
					mul r0.w, r2.y, cb4[18].w
					mad r0.w, cb4[17].w, r2.x, r0.w
					mad r0.w, cb4[19].w, r2.z, r0.w
					mad r0.w, cb4[20].w, r2.w, r0.w
					mul r2.xy, cb1[6].yyyy, cb4[6].xyxx
					mad r2.xy, cb4[5].xyxx, cb1[6].xxxx, r2.xyxx
					mul r2.xy, r2.xyxx, cb0[30].yzyy
					div r2.xy, r0.wwww, r2.xyxx
					dp2 r0.w, r2.xyxx, r2.xyxx
					rsq r0.w, r0.w
					mul r1.w, |v4.y|, cb0[30].x
					mul r0.w, r0.w, r1.w
					mul r1.w, r0.w, l(1.500000)
					add r2.x, -cb0[30].w, l(1.000000)
					mul r1.w, r1.w, r2.x
					mad r0.w, r0.w, l(1.500000), -r1.w
					mul r2.xyz, cb1[4].yyyy, cb3[5].xyzx
					mad r2.xyz, cb3[4].xyzx, cb1[4].xxxx, r2.xyzx
					mad r2.xyz, cb3[6].xyzx, cb1[4].zzzz, r2.xyzx
					add r2.xyz, r2.xyzx, cb3[7].xyzx
					mov r0.z, v0.z
					add r0.xyz, -r0.xyzx, r2.xyzx
					dp3 r0.x, v2.xyzx, r0.xyzx
					lt r0.y, l(0.000000), r0.x
					lt r0.x, r0.x, l(0.000000)
					iadd r0.x, -r0.y, r0.x
					itof r0.x, r0.x
					mul r0.xyz, r0.xxxx, v2.xyzx
					dp3 r2.x, r0.xyzx, cb3[4].xyzx
					dp3 r2.y, r0.xyzx, cb3[5].xyzx
					dp3 r2.z, r0.xyzx, cb3[6].xyzx
					dp3 r0.x, r2.xyzx, r2.xyzx
					rsq r0.x, r0.x
					mul r2.xyzw, r0.xxxx, r2.xyzz
					add r0.xyz, -r1.xyzx, cb1[4].xyzx
					dp3 r3.x, r0.xyzx, r0.xyzx
					rsq r3.x, r3.x
					mul r3.xyz, r0.xyzx, r3.xxxx
					dp3 r3.x, r2.xywx, r3.xyzx
					mad o2.w, |r3.x|, r0.w, r1.w
					mov o3.w, r1.x
					mul r3.xyz, v1.yyyy, cb3[1].yzxy
					mad r3.xyz, cb3[0].yzxy, v1.xxxx, r3.xyzx
					mad r3.xyz, cb3[2].yzxy, v1.zzzz, r3.xyzx
					dp3 r0.w, r3.xyzx, r3.xyzx
					rsq r0.w, r0.w
					mul r3.xyz, r0.wwww, r3.xyzx
					mul r4.xyz, r2.wxyw, r3.xyzx
					mad r4.xyz, r2.ywxy, r3.yzxy, -r4.xyzx
					mul r0.w, v1.w, cb3[9].w
					mul r4.xyz, r0.wwww, r4.xyzx
					mov o3.y, r4.x
					mov o3.z, r2.x
					mov o3.x, r3.z
					mov o4.x, r3.x
					mov o5.x, r3.y
					mov o4.w, r1.y
					mov o5.w, r1.z
					mov o4.z, r2.y
					mov o4.y, r4.y
					mov o5.y, r4.z
					mov o5.z, r2.w
					mov o6.xyzw, v7.xyzw
					mul r1.xyz, r0.yyyy, cb0[14].xyzx
					mad r0.xyw, cb0[13].xyxz, r0.xxxx, r1.xyxz
					mad o7.xyz, cb0[15].xyzx, r0.zzzz, r0.xywx
					mul r0.x, r2.y, r2.y
					mad r0.x, r2.x, r2.x, -r0.x
					mul r1.xyzw, r2.ywzx, r2.xyzw
					dp4 r2.x, cb2[42].xyzw, r1.xyzw
					dp4 r2.y, cb2[43].xyzw, r1.xyzw
					dp4 r2.z, cb2[44].xyzw, r1.xyzw
					mad o8.xyz, cb2[45].xyzx, r0.xxxx, r2.xyzx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" "LIGHTPROBE_SH" "VERTEXLIGHT_ON" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// TANGENT                  0   xyzw        1     NONE   float   xyzw
					// NORMAL                   0   xyz         2     NONE   float   xyz 
					// TEXCOORD                 0   xyzw        3     NONE   float   xy  
					// TEXCOORD                 1   xyzw        4     NONE   float   xy  
					// TEXCOORD                 2   xyzw        5     NONE   float       
					// TEXCOORD                 3   xyzw        6     NONE   float       
					// COLOR                    0   xyzw        7     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 1   xy          2     NONE   float   xy  
					// TEXCOORD                 5     zw        2     NONE   float     zw
					// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
					// TEXCOORD                 3   xyzw        4     NONE   float   xyzw
					// TEXCOORD                 4   xyzw        5     NONE   float   xyzw
					// COLOR                    0   xyzw        6     NONE   float   xyzw
					// TEXCOORD                 6   xyz         7     NONE   float   xyz 
					// TEXCOORD                 7   xyz         8     NONE   float   xyz 
					//
					vs_4_0
					dcl_constantbuffer CB0[35], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_constantbuffer CB2[46], immediateIndexed
					dcl_constantbuffer CB3[10], immediateIndexed
					dcl_constantbuffer CB4[21], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xyzw
					dcl_input v2.xyz
					dcl_input v3.xy
					dcl_input v4.xy
					dcl_input v7.xyzw
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xy
					dcl_output o2.zw
					dcl_output o3.xyzw
					dcl_output o4.xyzw
					dcl_output o5.xyzw
					dcl_output o6.xyzw
					dcl_output o7.xyz
					dcl_output o8.xyz
					dcl_temps 5
					add r0.xy, v0.xyxx, cb0[25].zwzz
					mul r1.xyzw, r0.yyyy, cb3[1].xyzw
					mad r1.xyzw, cb3[0].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb3[2].xyzw, v0.zzzz, r1.xyzw
					add r2.xyzw, r1.xyzw, cb3[3].xyzw
					mad r1.xyz, cb3[3].xyzx, v0.wwww, r1.xyzx
					mul r3.xyzw, r2.yyyy, cb4[18].xyzw
					mad r3.xyzw, cb4[17].xyzw, r2.xxxx, r3.xyzw
					mad r3.xyzw, cb4[19].xyzw, r2.zzzz, r3.xyzw
					mad o0.xyzw, cb4[20].xyzw, r2.wwww, r3.xyzw
					mul r0.w, v4.x, l(0.000244)
					round_ni r3.x, r0.w
					mad r3.y, -r3.x, l(4096.000000), v4.x
					mul r3.xy, r3.xyxx, l(0.001953, 0.001953, 0.000000, 0.000000)
					mad o1.zw, r3.xxxy, cb0[33].xxxy, cb0[33].zzzw
					mad o2.xy, r3.xyxx, cb0[34].xyxx, cb0[34].zwzz
					mad o1.xy, v3.xyxx, cb0[32].xyxx, cb0[32].zwzz
					ge r0.w, l(0.000000), v4.y
					and r0.w, r0.w, l(0x3f800000)
					add r1.w, -cb0[24].y, cb0[24].z
					mad r0.w, r0.w, r1.w, cb0[24].y
					mad r0.w, r0.w, l(0.250000), cb0[6].x
					mul r0.w, r0.w, cb0[24].w
					mul o2.z, r0.w, l(0.500000)
					mul r0.w, r2.y, cb4[18].w
					mad r0.w, cb4[17].w, r2.x, r0.w
					mad r0.w, cb4[19].w, r2.z, r0.w
					mad r0.w, cb4[20].w, r2.w, r0.w
					mul r2.xy, cb1[6].yyyy, cb4[6].xyxx
					mad r2.xy, cb4[5].xyxx, cb1[6].xxxx, r2.xyxx
					mul r2.xy, r2.xyxx, cb0[30].yzyy
					div r2.xy, r0.wwww, r2.xyxx
					dp2 r0.w, r2.xyxx, r2.xyxx
					rsq r0.w, r0.w
					mul r1.w, |v4.y|, cb0[30].x
					mul r0.w, r0.w, r1.w
					mul r1.w, r0.w, l(1.500000)
					add r2.x, -cb0[30].w, l(1.000000)
					mul r1.w, r1.w, r2.x
					mad r0.w, r0.w, l(1.500000), -r1.w
					mul r2.xyz, cb1[4].yyyy, cb3[5].xyzx
					mad r2.xyz, cb3[4].xyzx, cb1[4].xxxx, r2.xyzx
					mad r2.xyz, cb3[6].xyzx, cb1[4].zzzz, r2.xyzx
					add r2.xyz, r2.xyzx, cb3[7].xyzx
					mov r0.z, v0.z
					add r0.xyz, -r0.xyzx, r2.xyzx
					dp3 r0.x, v2.xyzx, r0.xyzx
					lt r0.y, l(0.000000), r0.x
					lt r0.x, r0.x, l(0.000000)
					iadd r0.x, -r0.y, r0.x
					itof r0.x, r0.x
					mul r0.xyz, r0.xxxx, v2.xyzx
					dp3 r2.x, r0.xyzx, cb3[4].xyzx
					dp3 r2.y, r0.xyzx, cb3[5].xyzx
					dp3 r2.z, r0.xyzx, cb3[6].xyzx
					dp3 r0.x, r2.xyzx, r2.xyzx
					rsq r0.x, r0.x
					mul r2.xyzw, r0.xxxx, r2.xyzz
					add r0.xyz, -r1.xyzx, cb1[4].xyzx
					dp3 r3.x, r0.xyzx, r0.xyzx
					rsq r3.x, r3.x
					mul r3.xyz, r0.xyzx, r3.xxxx
					dp3 r3.x, r2.xywx, r3.xyzx
					mad o2.w, |r3.x|, r0.w, r1.w
					mul r3.xyz, v1.yyyy, cb3[1].yzxy
					mad r3.xyz, cb3[0].yzxy, v1.xxxx, r3.xyzx
					mad r3.xyz, cb3[2].yzxy, v1.zzzz, r3.xyzx
					dp3 r0.w, r3.xyzx, r3.xyzx
					rsq r0.w, r0.w
					mul r3.xyz, r0.wwww, r3.xyzx
					mul r4.xyz, r2.wxyw, r3.xyzx
					mad r4.xyz, r2.ywxy, r3.yzxy, -r4.xyzx
					mul r0.w, v1.w, cb3[9].w
					mul r4.xyz, r0.wwww, r4.xyzx
					mov o3.y, r4.x
					mov o3.z, r2.x
					mov o3.x, r3.z
					mov o3.w, r1.x
					mov o4.x, r3.x
					mov o5.x, r3.y
					mov o4.z, r2.y
					mov o4.y, r4.y
					mov o5.y, r4.z
					mov o4.w, r1.y
					mov o5.z, r2.w
					mov o5.w, r1.z
					mov o6.xyzw, v7.xyzw
					mul r3.xyz, r0.yyyy, cb0[14].xyzx
					mad r0.xyw, cb0[13].xyxz, r0.xxxx, r3.xyxz
					mad o7.xyz, cb0[15].xyzx, r0.zzzz, r0.xywx
					add r0.xyzw, -r1.yyyy, cb2[4].xyzw
					mul r3.xyzw, r2.yyyy, r0.xyzw
					mul r0.xyzw, r0.xyzw, r0.xyzw
					add r4.xyzw, -r1.xxxx, cb2[3].xyzw
					add r1.xyzw, -r1.zzzz, cb2[5].xyzw
					mad r3.xyzw, r4.xyzw, r2.xxxx, r3.xyzw
					mad r0.xyzw, r4.xyzw, r4.xyzw, r0.xyzw
					mad r0.xyzw, r1.xyzw, r1.xyzw, r0.xyzw
					mad r1.xyzw, r1.xyzw, r2.wwzw, r3.xyzw
					max r0.xyzw, r0.xyzw, l(0.000001, 0.000001, 0.000001, 0.000001)
					rsq r3.xyzw, r0.xyzw
					mad r0.xyzw, r0.xyzw, cb2[6].xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
					div r0.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000), r0.xyzw
					mul r1.xyzw, r1.xyzw, r3.xyzw
					max r1.xyzw, r1.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000)
					mul r0.xyzw, r0.xyzw, r1.xyzw
					mul r1.xyz, r0.yyyy, cb2[8].xyzx
					mad r1.xyz, cb2[7].xyzx, r0.xxxx, r1.xyzx
					mad r0.xyz, cb2[9].xyzx, r0.zzzz, r1.xyzx
					mad r0.xyz, cb2[10].xyzx, r0.wwww, r0.xyzx
					mad r1.xyz, r0.xyzx, l(0.305306, 0.305306, 0.305306, 0.000000), l(0.682171, 0.682171, 0.682171, 0.000000)
					mad r1.xyz, r0.xyzx, r1.xyzx, l(0.012523, 0.012523, 0.012523, 0.000000)
					mul r0.w, r2.y, r2.y
					mad r0.w, r2.x, r2.x, -r0.w
					mul r2.xyzw, r2.ywzx, r2.xyzw
					dp4 r3.x, cb2[42].xyzw, r2.xyzw
					dp4 r3.y, cb2[43].xyzw, r2.xyzw
					dp4 r3.z, cb2[44].xyzw, r2.xyzw
					mad r2.xyz, cb2[45].xyzx, r0.wwww, r3.xyzx
					mad o8.xyz, r0.xyzx, r1.xyzx, r2.xyzx
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 1   xy          2     NONE   float   xy  
					// TEXCOORD                 5     zw        2     NONE   float     zw
					// TEXCOORD                 2   xyzw        3     NONE   float     z 
					// TEXCOORD                 3   xyzw        4     NONE   float     z 
					// TEXCOORD                 4   xyzw        5     NONE   float     z 
					// COLOR                    0   xyzw        6     NONE   float   xyzw
					// TEXCOORD                 6   xyz         7     NONE   float       
					// TEXCOORD                 7   xyz         8     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[25], immediateIndexed
					dcl_constantbuffer CB1[1], immediateIndexed
					dcl_constantbuffer CB2[42], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_sampler s2, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_resource_texture2d (float,float,float,float) t2
					dcl_input_ps linear v1.xyzw
					dcl_input_ps linear v2.xy
					dcl_input_ps linear v2.zw
					dcl_input_ps linear v3.z
					dcl_input_ps linear v4.z
					dcl_input_ps linear v5.z
					dcl_input_ps linear v6.xyzw
					dcl_input_ps linear v8.xyz
					dcl_output o0.xyzw
					dcl_temps 3
					mad r0.xy, cb0[6].zwzz, cb1[0].yyyy, v2.xyxx
					sample r0.xyzw, r0.xyxx, t2.xyzw, s1
					mul r0.xyz, r0.xyzx, cb0[7].xyzx
					mul r1.x, v6.w, cb0[7].w
					mul r1.w, r0.w, r1.x
					mul r1.xyz, r0.xyzx, r1.wwww
					mad r0.xy, cb0[4].xyxx, cb1[0].yyyy, v1.zwzz
					sample r0.xyzw, r0.xyxx, t1.xyzw, s0
					mul r2.xyzw, v6.xyzw, cb0[5].xyzw
					mul r0.xyzw, r0.xyzw, r2.xyzw
					mul r0.xyz, r0.wwww, r0.xyzx
					add r1.xyzw, -r0.xyzw, r1.xyzw
					sample r2.xyzw, v1.xyxx, t0.xyzw, s2
					add r2.x, -r2.w, l(0.500000)
					add r2.x, r2.x, -v2.z
					mad r2.x, r2.x, v2.w, l(0.500000)
					mul r2.y, cb0[8].x, cb0[24].w
					mul r2.y, r2.y, v2.w
					mad_sat r2.z, r2.y, l(0.500000), r2.x
					mad r2.x, -r2.y, l(0.500000), r2.x
					min r2.y, r2.y, l(1.000000)
					sqrt r2.y, r2.y
					mul r2.y, r2.y, r2.z
					mad r0.xyzw, r2.yyyy, r1.xyzw, r0.xyzw
					mul r1.x, cb0[6].y, cb0[24].w
					mul r1.y, r1.x, v2.w
					mad r1.x, r1.x, v2.w, l(1.000000)
					mad r1.y, r1.y, l(0.500000), r2.x
					div_sat r1.x, r1.y, r1.x
					add r1.x, -r1.x, l(1.000000)
					mul r0.xyzw, r0.xyzw, r1.xxxx
					max r1.x, r0.w, l(0.000100)
					div r0.xyz, r0.xyzx, r1.xxxx
					mov o0.w, r0.w
					mov r1.x, v3.z
					mov r1.y, v4.z
					mov r1.z, v5.z
					dp3 r0.w, r1.xyzx, r1.xyzx
					rsq r0.w, r0.w
					mul r1.xyz, r0.wwww, r1.xyzx
					mov r1.w, l(1.000000)
					dp4 r2.x, cb2[39].xyzw, r1.xyzw
					dp4 r2.y, cb2[40].xyzw, r1.xyzw
					dp4 r2.z, cb2[41].xyzw, r1.xyzw
					dp3 r0.w, r1.xyzx, cb2[0].xyzx
					max r0.w, r0.w, l(0.000000)
					add r1.xyz, r2.xyzx, v8.xyzx
					max r1.xyz, r1.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
					log r1.xyz, r1.xyzx
					mul r1.xyz, r1.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
					exp r1.xyz, r1.xyzx
					mad r1.xyz, r1.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000), l(-0.055000, -0.055000, -0.055000, 0.000000)
					max r1.xyz, r1.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
					mul r1.xyz, r0.xyzx, r1.xyzx
					mul r0.xyz, r0.xyzx, cb0[2].xyzx
					mad o0.xyz, r0.xyzx, r0.wwww, r1.xyzx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "DIRECTIONAL" "LIGHTPROBE_SH" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 1   xy          2     NONE   float   xy  
					// TEXCOORD                 5     zw        2     NONE   float     zw
					// TEXCOORD                 2   xyzw        3     NONE   float     z 
					// TEXCOORD                 3   xyzw        4     NONE   float     z 
					// TEXCOORD                 4   xyzw        5     NONE   float     z 
					// COLOR                    0   xyzw        6     NONE   float   xyzw
					// TEXCOORD                 6   xyz         7     NONE   float       
					// TEXCOORD                 7   xyz         8     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[25], immediateIndexed
					dcl_constantbuffer CB1[1], immediateIndexed
					dcl_constantbuffer CB2[42], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_sampler s2, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_resource_texture2d (float,float,float,float) t2
					dcl_input_ps linear v1.xyzw
					dcl_input_ps linear v2.xy
					dcl_input_ps linear v2.zw
					dcl_input_ps linear v3.z
					dcl_input_ps linear v4.z
					dcl_input_ps linear v5.z
					dcl_input_ps linear v6.xyzw
					dcl_input_ps linear v8.xyz
					dcl_output o0.xyzw
					dcl_temps 3
					mad r0.xy, cb0[6].zwzz, cb1[0].yyyy, v2.xyxx
					sample r0.xyzw, r0.xyxx, t2.xyzw, s1
					mul r0.xyz, r0.xyzx, cb0[7].xyzx
					mul r1.x, v6.w, cb0[7].w
					mul r1.w, r0.w, r1.x
					mul r1.xyz, r0.xyzx, r1.wwww
					mad r0.xy, cb0[4].xyxx, cb1[0].yyyy, v1.zwzz
					sample r0.xyzw, r0.xyxx, t1.xyzw, s0
					mul r2.xyzw, v6.xyzw, cb0[5].xyzw
					mul r0.xyzw, r0.xyzw, r2.xyzw
					mul r0.xyz, r0.wwww, r0.xyzx
					add r1.xyzw, -r0.xyzw, r1.xyzw
					sample r2.xyzw, v1.xyxx, t0.xyzw, s2
					add r2.x, -r2.w, l(0.500000)
					add r2.x, r2.x, -v2.z
					mad r2.x, r2.x, v2.w, l(0.500000)
					mul r2.y, cb0[8].x, cb0[24].w
					mul r2.y, r2.y, v2.w
					mad_sat r2.z, r2.y, l(0.500000), r2.x
					mad r2.x, -r2.y, l(0.500000), r2.x
					min r2.y, r2.y, l(1.000000)
					sqrt r2.y, r2.y
					mul r2.y, r2.y, r2.z
					mad r0.xyzw, r2.yyyy, r1.xyzw, r0.xyzw
					mul r1.x, cb0[6].y, cb0[24].w
					mul r1.y, r1.x, v2.w
					mad r1.x, r1.x, v2.w, l(1.000000)
					mad r1.y, r1.y, l(0.500000), r2.x
					div_sat r1.x, r1.y, r1.x
					add r1.x, -r1.x, l(1.000000)
					mul r0.xyzw, r0.xyzw, r1.xxxx
					max r1.x, r0.w, l(0.000100)
					div r0.xyz, r0.xyzx, r1.xxxx
					mov o0.w, r0.w
					mov r1.x, v3.z
					mov r1.y, v4.z
					mov r1.z, v5.z
					dp3 r0.w, r1.xyzx, r1.xyzx
					rsq r0.w, r0.w
					mul r1.xyz, r0.wwww, r1.xyzx
					mov r1.w, l(1.000000)
					dp4 r2.x, cb2[39].xyzw, r1.xyzw
					dp4 r2.y, cb2[40].xyzw, r1.xyzw
					dp4 r2.z, cb2[41].xyzw, r1.xyzw
					dp3 r0.w, r1.xyzx, cb2[0].xyzx
					max r0.w, r0.w, l(0.000000)
					add r1.xyz, r2.xyzx, v8.xyzx
					max r1.xyz, r1.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
					log r1.xyz, r1.xyzx
					mul r1.xyz, r1.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
					exp r1.xyz, r1.xyzx
					mad r1.xyz, r1.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000), l(-0.055000, -0.055000, -0.055000, 0.000000)
					max r1.xyz, r1.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
					mul r1.xyz, r0.xyzx, r1.xyzx
					mul r0.xyz, r0.xyzx, cb0[2].xyzx
					mad o0.xyz, r0.xyzx, r0.wwww, r1.xyzx
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
		Pass {
			Name "Caster"
			LOD 300
			Tags { "IGNOREPROJECTOR" = "true" "LIGHTMODE" = "SHADOWCASTER" "QUEUE" = "Transparent" "RenderType" = "Transparent" "SHADOWSUPPORT" = "true" }
			ColorMask RGB -1
			Cull Off
			Offset 1, 1
			Fog {
				Mode Off
			}
			GpuProgramID 103558
			Program "vp" {
				SubProgram "d3d11 " {
					Keywords { "SHADOWS_DEPTH" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// NORMAL                   0   xyz         1     NONE   float       
					// TEXCOORD                 0   xyzw        2     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 1   xy          1     NONE   float   xy  
					// TEXCOORD                 3     zw        1     NONE   float     zw
					// TEXCOORD                 2   x           2     NONE   float   x   
					//
					vs_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_constantbuffer CB1[6], immediateIndexed
					dcl_constantbuffer CB2[4], immediateIndexed
					dcl_constantbuffer CB3[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v2.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_output o1.zw
					dcl_output o2.x
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb2[1].xyzw
					mad r0.xyzw, cb2[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb2[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb2[3].xyzw
					mul r1.xyzw, r0.yyyy, cb3[18].xyzw
					mad r1.xyzw, cb3[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb3[19].xyzw, r0.zzzz, r1.xyzw
					mad r0.xyzw, cb3[20].xyzw, r0.wwww, r1.xyzw
					div r1.x, cb1[5].x, r0.w
					min r1.x, r1.x, l(0.000000)
					max r1.x, r1.x, l(-1.000000)
					add r0.z, r0.z, r1.x
					min r1.x, r0.w, r0.z
					mov o0.xyw, r0.xyxw
					add r0.x, -r0.z, r1.x
					mad o0.z, cb1[5].y, r0.x, r0.z
					mad o1.xy, v2.xyxx, cb0[2].xyxx, cb0[2].zwzz
					mad o1.zw, v2.xxxy, cb0[3].xxxy, cb0[3].zzzw
					mad r0.x, -cb0[4].x, cb0[4].z, l(1.000000)
					mad r0.x, -cb0[4].y, cb0[4].z, r0.x
					mul o2.x, r0.x, l(0.500000)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "SHADOWS_CUBE" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// NORMAL                   0   xyz         1     NONE   float       
					// TEXCOORD                 0   xyzw        2     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 1   xy          1     NONE   float   xy  
					// TEXCOORD                 3     zw        1     NONE   float     zw
					// TEXCOORD                 2   x           2     NONE   float   x   
					//
					vs_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_constantbuffer CB1[6], immediateIndexed
					dcl_constantbuffer CB2[4], immediateIndexed
					dcl_constantbuffer CB3[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v2.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_output o1.zw
					dcl_output o2.x
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb2[1].xyzw
					mad r0.xyzw, cb2[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb2[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb2[3].xyzw
					mul r1.xyzw, r0.yyyy, cb3[18].xyzw
					mad r1.xyzw, cb3[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb3[19].xyzw, r0.zzzz, r1.xyzw
					mad r0.xyzw, cb3[20].xyzw, r0.wwww, r1.xyzw
					min r1.x, r0.w, r0.z
					add r1.x, -r0.z, r1.x
					mad o0.z, cb1[5].y, r1.x, r0.z
					mov o0.xyw, r0.xyxw
					mad o1.xy, v2.xyxx, cb0[2].xyxx, cb0[2].zwzz
					mad o1.zw, v2.xxxy, cb0[3].xxxy, cb0[3].zzzw
					mad r0.x, -cb0[4].x, cb0[4].z, l(1.000000)
					mad r0.x, -cb0[4].y, cb0[4].z, r0.x
					mul o2.x, r0.x, l(0.500000)
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					Keywords { "SHADOWS_DEPTH" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 1   xy          1     NONE   float   xy  
					// TEXCOORD                 3     zw        1     NONE   float       
					// TEXCOORD                 2   x           2     NONE   float   x   
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xy
					dcl_input_ps linear v2.x
					dcl_output o0.xyzw
					dcl_temps 1
					sample r0.xyzw, v1.xyxx, t0.xyzw, s0
					add r0.x, r0.w, -v2.x
					lt r0.x, r0.x, l(0.000000)
					discard_nz r0.x
					mov o0.xyzw, l(0,0,0,0)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "SHADOWS_CUBE" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 1   xy          1     NONE   float   xy  
					// TEXCOORD                 3     zw        1     NONE   float       
					// TEXCOORD                 2   x           2     NONE   float   x   
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xy
					dcl_input_ps linear v2.x
					dcl_output o0.xyzw
					dcl_temps 1
					sample r0.xyzw, v1.xyxx, t0.xyzw, s0
					add r0.x, r0.w, -v2.x
					lt r0.x, r0.x, l(0.000000)
					discard_nz r0.x
					mov o0.xyzw, l(0,0,0,0)
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
	CustomEditor "TMPro.EditorUtilities.TMP_SDFShaderGUI"
}