Shader "TextMeshPro/Mobile/Distance Field - Masking" {
	Properties {
		_FaceColor ("Face Color", Vector) = (1,1,1,1)
		_FaceDilate ("Face Dilate", Range(-1, 1)) = 0
		_OutlineColor ("Outline Color", Vector) = (0,0,0,1)
		_OutlineWidth ("Outline Thickness", Range(0, 1)) = 0
		_OutlineSoftness ("Outline Softness", Range(0, 1)) = 0
		_UnderlayColor ("Border Color", Vector) = (0,0,0,0.5)
		_UnderlayOffsetX ("Border OffsetX", Range(-1, 1)) = 0
		_UnderlayOffsetY ("Border OffsetY", Range(-1, 1)) = 0
		_UnderlayDilate ("Border Dilate", Range(-1, 1)) = 0
		_UnderlaySoftness ("Border Softness", Range(0, 1)) = 0
		_WeightNormal ("Weight Normal", Float) = 0
		_WeightBold ("Weight Bold", Float) = 0.5
		_ShaderFlags ("Flags", Float) = 0
		_ScaleRatioA ("Scale RatioA", Float) = 1
		_ScaleRatioB ("Scale RatioB", Float) = 1
		_ScaleRatioC ("Scale RatioC", Float) = 1
		_MainTex ("Font Atlas", 2D) = "white" {}
		_TextureWidth ("Texture Width", Float) = 512
		_TextureHeight ("Texture Height", Float) = 512
		_GradientScale ("Gradient Scale", Float) = 5
		_ScaleX ("Scale X", Float) = 1
		_ScaleY ("Scale Y", Float) = 1
		_PerspectiveFilter ("Perspective Correction", Range(0, 1)) = 0.875
		_VertexOffsetX ("Vertex OffsetX", Float) = 0
		_VertexOffsetY ("Vertex OffsetY", Float) = 0
		_ClipRect ("Clip Rect", Vector) = (-32767,-32767,32767,32767)
		_MaskSoftnessX ("Mask SoftnessX", Float) = 0
		_MaskSoftnessY ("Mask SoftnessY", Float) = 0
		_MaskTex ("Mask Texture", 2D) = "white" {}
		_MaskInverse ("Inverse", Float) = 0
		_MaskEdgeColor ("Edge Color", Vector) = (1,1,1,1)
		_MaskEdgeSoftness ("Edge Softness", Range(0, 1)) = 0.01
		_MaskWipeControl ("Wipe Position", Range(0, 1)) = 0.5
		_StencilComp ("Stencil Comparison", Float) = 8
		_Stencil ("Stencil ID", Float) = 0
		_StencilOp ("Stencil Operation", Float) = 0
		_StencilWriteMask ("Stencil Write Mask", Float) = 255
		_StencilReadMask ("Stencil Read Mask", Float) = 255
		_ColorMask ("Color Mask", Float) = 15
	}
	SubShader {
		Tags { "IGNOREPROJECTOR" = "true" "QUEUE" = "Transparent" "RenderType" = "Transparent" }
		Pass {
			Tags { "IGNOREPROJECTOR" = "true" "QUEUE" = "Transparent" "RenderType" = "Transparent" }
			Blend One OneMinusSrcAlpha, One OneMinusSrcAlpha
			ColorMask 0 -1
			ZWrite Off
			Cull Off
			Stencil {
				ReadMask 0
				WriteMask 0
				Comp Disabled
				Pass Keep
				Fail Keep
				ZFail Keep
			}
			Fog {
				Mode Off
			}
			GpuProgramID 15606
			Program "vp" {
				SubProgram "d3d11 " {
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// NORMAL                   0   xyz         1     NONE   float   xyz 
					// COLOR                    0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 0   xy          3     NONE   float   xy  
					// TEXCOORD                 1   xy          4     NONE   float    y  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// COLOR                    1   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        3     NONE   float   xyzw
					// TEXCOORD                 1   xyzw        4     NONE   float   xyzw
					// TEXCOORD                 2   xyzw        5     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[29], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_constantbuffer CB2[7], immediateIndexed
					dcl_constantbuffer CB3[21], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xyz
					dcl_input v2.xyzw
					dcl_input v3.xy
					dcl_input v4.y
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_output o3.xyzw
					dcl_output o4.xyzw
					dcl_output o5.xyzw
					dcl_temps 5
					add r0.xy, v0.xyxx, cb0[23].zwzz
					mul r1.xyzw, r0.yyyy, cb2[1].xyzw
					mad r1.xyzw, cb2[0].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[2].xyzw, v0.zzzz, r1.xyzw
					add r2.xyzw, r1.xyzw, cb2[3].xyzw
					mad r1.xyz, cb2[3].xyzx, v0.wwww, r1.xyzx
					add r1.xyz, -r1.xyzx, cb1[4].xyzx
					mul r3.xyzw, r2.yyyy, cb3[18].xyzw
					mad r3.xyzw, cb3[17].xyzw, r2.xxxx, r3.xyzw
					mad r3.xyzw, cb3[19].xyzw, r2.zzzz, r3.xyzw
					mad r2.xyzw, cb3[20].xyzw, r2.wwww, r3.xyzw
					mov o0.xyzw, r2.xyzw
					mul r3.xyzw, v2.xyzw, cb0[3].xyzw
					mul r3.xyz, r3.wwww, r3.xyzx
					mov o1.xyzw, r3.xyzw
					mul r4.w, v2.w, cb0[5].w
					mul r4.xyz, r4.wwww, cb0[5].xyzx
					add r4.xyzw, -r3.xyzw, r4.xyzw
					dp3 r0.z, r1.xyzx, r1.xyzx
					rsq r0.z, r0.z
					mul r1.xyz, r0.zzzz, r1.xyzx
					dp3 r2.x, v1.xyzx, cb2[4].xyzx
					dp3 r2.y, v1.xyzx, cb2[5].xyzx
					dp3 r2.z, v1.xyzx, cb2[6].xyzx
					dp3 r0.z, r2.xyzx, r2.xyzx
					rsq r0.z, r0.z
					mul r2.xyz, r0.zzzz, r2.xyzx
					dp3 r0.z, r2.xyzx, r1.xyzx
					mul r1.xy, cb1[6].yyyy, cb3[6].xyxx
					mad r1.xy, cb3[5].xyxx, cb1[6].xxxx, r1.xyxx
					mul r1.xy, |r1.xyxx|, cb0[28].yzyy
					div r1.xy, r2.wwww, r1.xyxx
					dp2 r0.w, r1.xyxx, r1.xyxx
					mad r1.xy, cb0[27].xyxx, l(0.250000, 0.250000, 0.000000, 0.000000), r1.xyxx
					div o5.zw, l(0.000000, 0.000000, 0.250000, 0.250000), r1.xxxy
					rsq r0.w, r0.w
					mul r1.x, |v4.y|, cb0[28].x
					mul r0.w, r0.w, r1.x
					mul r1.x, r0.w, l(1.500000)
					add r1.y, -cb0[28].w, l(1.000000)
					mul r1.y, r1.y, |r1.x|
					mad r0.w, r0.w, l(1.500000), -r1.y
					mad r0.z, |r0.z|, r0.w, r1.y
					eq r0.w, cb3[8].w, l(0.000000)
					movc r0.z, r0.w, r0.z, r1.x
					mul r0.w, cb0[4].y, cb0[22].w
					mad r0.w, r0.w, r0.z, l(1.000000)
					div r1.x, r0.z, r0.w
					mul r0.z, cb0[6].x, cb0[22].w
					mul r0.z, r0.z, l(0.500000)
					mul r0.w, r1.x, r0.z
					add r0.w, r0.w, r0.w
					min r0.w, r0.w, l(1.000000)
					sqrt r0.w, r0.w
					mad o2.xyzw, r0.wwww, r4.xyzw, r3.xyzw
					max r2.xyzw, cb0[26].xyzw, l(-20000000000.000000, -20000000000.000000, -20000000000.000000, -20000000000.000000)
					min r2.xyzw, r2.xyzw, l(20000000000.000000, 20000000000.000000, 20000000000.000000, 20000000000.000000)
					add r1.yz, r0.xxyx, -r2.xxyx
					mad r0.xy, r0.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), -r2.xyxx
					add o5.xy, -r2.zwzz, r0.xyxx
					add r0.xy, -r2.xyxx, r2.zwzz
					div o3.zw, r1.yyyz, r0.xxxy
					mov o3.xy, v3.xyxx
					ge r0.x, l(0.000000), v4.y
					and r0.x, r0.x, l(0x3f800000)
					add r0.y, -cb0[22].y, cb0[22].z
					mad r0.x, r0.x, r0.y, cb0[22].y
					mad r0.x, r0.x, l(0.250000), cb0[4].x
					mul r0.x, r0.x, cb0[22].w
					mad r0.x, -r0.x, l(0.500000), l(0.500000)
					mad r1.w, r0.x, r1.x, l(-0.500000)
					mad o4.y, -r0.z, r1.x, r1.w
					mad o4.z, r0.z, r1.x, r1.w
					mov o4.xw, r1.xxxw
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "UNITY_UI_ALPHACLIP" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// NORMAL                   0   xyz         1     NONE   float   xyz 
					// COLOR                    0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 0   xy          3     NONE   float   xy  
					// TEXCOORD                 1   xy          4     NONE   float    y  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// COLOR                    1   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        3     NONE   float   xyzw
					// TEXCOORD                 1   xyzw        4     NONE   float   xyzw
					// TEXCOORD                 2   xyzw        5     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[29], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_constantbuffer CB2[7], immediateIndexed
					dcl_constantbuffer CB3[21], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xyz
					dcl_input v2.xyzw
					dcl_input v3.xy
					dcl_input v4.y
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_output o3.xyzw
					dcl_output o4.xyzw
					dcl_output o5.xyzw
					dcl_temps 5
					add r0.xy, v0.xyxx, cb0[23].zwzz
					mul r1.xyzw, r0.yyyy, cb2[1].xyzw
					mad r1.xyzw, cb2[0].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[2].xyzw, v0.zzzz, r1.xyzw
					add r2.xyzw, r1.xyzw, cb2[3].xyzw
					mad r1.xyz, cb2[3].xyzx, v0.wwww, r1.xyzx
					add r1.xyz, -r1.xyzx, cb1[4].xyzx
					mul r3.xyzw, r2.yyyy, cb3[18].xyzw
					mad r3.xyzw, cb3[17].xyzw, r2.xxxx, r3.xyzw
					mad r3.xyzw, cb3[19].xyzw, r2.zzzz, r3.xyzw
					mad r2.xyzw, cb3[20].xyzw, r2.wwww, r3.xyzw
					mov o0.xyzw, r2.xyzw
					mul r3.xyzw, v2.xyzw, cb0[3].xyzw
					mul r3.xyz, r3.wwww, r3.xyzx
					mov o1.xyzw, r3.xyzw
					mul r4.w, v2.w, cb0[5].w
					mul r4.xyz, r4.wwww, cb0[5].xyzx
					add r4.xyzw, -r3.xyzw, r4.xyzw
					dp3 r0.z, r1.xyzx, r1.xyzx
					rsq r0.z, r0.z
					mul r1.xyz, r0.zzzz, r1.xyzx
					dp3 r2.x, v1.xyzx, cb2[4].xyzx
					dp3 r2.y, v1.xyzx, cb2[5].xyzx
					dp3 r2.z, v1.xyzx, cb2[6].xyzx
					dp3 r0.z, r2.xyzx, r2.xyzx
					rsq r0.z, r0.z
					mul r2.xyz, r0.zzzz, r2.xyzx
					dp3 r0.z, r2.xyzx, r1.xyzx
					mul r1.xy, cb1[6].yyyy, cb3[6].xyxx
					mad r1.xy, cb3[5].xyxx, cb1[6].xxxx, r1.xyxx
					mul r1.xy, |r1.xyxx|, cb0[28].yzyy
					div r1.xy, r2.wwww, r1.xyxx
					dp2 r0.w, r1.xyxx, r1.xyxx
					mad r1.xy, cb0[27].xyxx, l(0.250000, 0.250000, 0.000000, 0.000000), r1.xyxx
					div o5.zw, l(0.000000, 0.000000, 0.250000, 0.250000), r1.xxxy
					rsq r0.w, r0.w
					mul r1.x, |v4.y|, cb0[28].x
					mul r0.w, r0.w, r1.x
					mul r1.x, r0.w, l(1.500000)
					add r1.y, -cb0[28].w, l(1.000000)
					mul r1.y, r1.y, |r1.x|
					mad r0.w, r0.w, l(1.500000), -r1.y
					mad r0.z, |r0.z|, r0.w, r1.y
					eq r0.w, cb3[8].w, l(0.000000)
					movc r0.z, r0.w, r0.z, r1.x
					mul r0.w, cb0[4].y, cb0[22].w
					mad r0.w, r0.w, r0.z, l(1.000000)
					div r1.x, r0.z, r0.w
					mul r0.z, cb0[6].x, cb0[22].w
					mul r0.z, r0.z, l(0.500000)
					mul r0.w, r1.x, r0.z
					add r0.w, r0.w, r0.w
					min r0.w, r0.w, l(1.000000)
					sqrt r0.w, r0.w
					mad o2.xyzw, r0.wwww, r4.xyzw, r3.xyzw
					max r2.xyzw, cb0[26].xyzw, l(-20000000000.000000, -20000000000.000000, -20000000000.000000, -20000000000.000000)
					min r2.xyzw, r2.xyzw, l(20000000000.000000, 20000000000.000000, 20000000000.000000, 20000000000.000000)
					add r1.yz, r0.xxyx, -r2.xxyx
					mad r0.xy, r0.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), -r2.xyxx
					add o5.xy, -r2.zwzz, r0.xyxx
					add r0.xy, -r2.xyxx, r2.zwzz
					div o3.zw, r1.yyyz, r0.xxxy
					mov o3.xy, v3.xyxx
					ge r0.x, l(0.000000), v4.y
					and r0.x, r0.x, l(0x3f800000)
					add r0.y, -cb0[22].y, cb0[22].z
					mad r0.x, r0.x, r0.y, cb0[22].y
					mad r0.x, r0.x, l(0.250000), cb0[4].x
					mul r0.x, r0.x, cb0[22].w
					mad r0.x, -r0.x, l(0.500000), l(0.500000)
					mad r1.w, r0.x, r1.x, l(-0.500000)
					mad o4.y, -r0.z, r1.x, r1.w
					mad o4.z, r0.z, r1.x, r1.w
					mov o4.xw, r1.xxxw
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "UNITY_UI_CLIP_RECT" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// NORMAL                   0   xyz         1     NONE   float   xyz 
					// COLOR                    0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 0   xy          3     NONE   float   xy  
					// TEXCOORD                 1   xy          4     NONE   float    y  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// COLOR                    1   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        3     NONE   float   xyzw
					// TEXCOORD                 1   xyzw        4     NONE   float   xyzw
					// TEXCOORD                 2   xyzw        5     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[29], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_constantbuffer CB2[7], immediateIndexed
					dcl_constantbuffer CB3[21], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xyz
					dcl_input v2.xyzw
					dcl_input v3.xy
					dcl_input v4.y
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_output o3.xyzw
					dcl_output o4.xyzw
					dcl_output o5.xyzw
					dcl_temps 5
					add r0.xy, v0.xyxx, cb0[23].zwzz
					mul r1.xyzw, r0.yyyy, cb2[1].xyzw
					mad r1.xyzw, cb2[0].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[2].xyzw, v0.zzzz, r1.xyzw
					add r2.xyzw, r1.xyzw, cb2[3].xyzw
					mad r1.xyz, cb2[3].xyzx, v0.wwww, r1.xyzx
					add r1.xyz, -r1.xyzx, cb1[4].xyzx
					mul r3.xyzw, r2.yyyy, cb3[18].xyzw
					mad r3.xyzw, cb3[17].xyzw, r2.xxxx, r3.xyzw
					mad r3.xyzw, cb3[19].xyzw, r2.zzzz, r3.xyzw
					mad r2.xyzw, cb3[20].xyzw, r2.wwww, r3.xyzw
					mov o0.xyzw, r2.xyzw
					mul r3.xyzw, v2.xyzw, cb0[3].xyzw
					mul r3.xyz, r3.wwww, r3.xyzx
					mov o1.xyzw, r3.xyzw
					mul r4.w, v2.w, cb0[5].w
					mul r4.xyz, r4.wwww, cb0[5].xyzx
					add r4.xyzw, -r3.xyzw, r4.xyzw
					dp3 r0.z, r1.xyzx, r1.xyzx
					rsq r0.z, r0.z
					mul r1.xyz, r0.zzzz, r1.xyzx
					dp3 r2.x, v1.xyzx, cb2[4].xyzx
					dp3 r2.y, v1.xyzx, cb2[5].xyzx
					dp3 r2.z, v1.xyzx, cb2[6].xyzx
					dp3 r0.z, r2.xyzx, r2.xyzx
					rsq r0.z, r0.z
					mul r2.xyz, r0.zzzz, r2.xyzx
					dp3 r0.z, r2.xyzx, r1.xyzx
					mul r1.xy, cb1[6].yyyy, cb3[6].xyxx
					mad r1.xy, cb3[5].xyxx, cb1[6].xxxx, r1.xyxx
					mul r1.xy, |r1.xyxx|, cb0[28].yzyy
					div r1.xy, r2.wwww, r1.xyxx
					dp2 r0.w, r1.xyxx, r1.xyxx
					mad r1.xy, cb0[27].xyxx, l(0.250000, 0.250000, 0.000000, 0.000000), r1.xyxx
					div o5.zw, l(0.000000, 0.000000, 0.250000, 0.250000), r1.xxxy
					rsq r0.w, r0.w
					mul r1.x, |v4.y|, cb0[28].x
					mul r0.w, r0.w, r1.x
					mul r1.x, r0.w, l(1.500000)
					add r1.y, -cb0[28].w, l(1.000000)
					mul r1.y, r1.y, |r1.x|
					mad r0.w, r0.w, l(1.500000), -r1.y
					mad r0.z, |r0.z|, r0.w, r1.y
					eq r0.w, cb3[8].w, l(0.000000)
					movc r0.z, r0.w, r0.z, r1.x
					mul r0.w, cb0[4].y, cb0[22].w
					mad r0.w, r0.w, r0.z, l(1.000000)
					div r1.x, r0.z, r0.w
					mul r0.z, cb0[6].x, cb0[22].w
					mul r0.z, r0.z, l(0.500000)
					mul r0.w, r1.x, r0.z
					add r0.w, r0.w, r0.w
					min r0.w, r0.w, l(1.000000)
					sqrt r0.w, r0.w
					mad o2.xyzw, r0.wwww, r4.xyzw, r3.xyzw
					max r2.xyzw, cb0[26].xyzw, l(-20000000000.000000, -20000000000.000000, -20000000000.000000, -20000000000.000000)
					min r2.xyzw, r2.xyzw, l(20000000000.000000, 20000000000.000000, 20000000000.000000, 20000000000.000000)
					add r1.yz, r0.xxyx, -r2.xxyx
					mad r0.xy, r0.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), -r2.xyxx
					add o5.xy, -r2.zwzz, r0.xyxx
					add r0.xy, -r2.xyxx, r2.zwzz
					div o3.zw, r1.yyyz, r0.xxxy
					mov o3.xy, v3.xyxx
					ge r0.x, l(0.000000), v4.y
					and r0.x, r0.x, l(0x3f800000)
					add r0.y, -cb0[22].y, cb0[22].z
					mad r0.x, r0.x, r0.y, cb0[22].y
					mad r0.x, r0.x, l(0.250000), cb0[4].x
					mul r0.x, r0.x, cb0[22].w
					mad r0.x, -r0.x, l(0.500000), l(0.500000)
					mad r1.w, r0.x, r1.x, l(-0.500000)
					mad o4.y, -r0.z, r1.x, r1.w
					mad o4.z, r0.z, r1.x, r1.w
					mov o4.xw, r1.xxxw
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "UNITY_UI_CLIP_RECT" "UNITY_UI_ALPHACLIP" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// NORMAL                   0   xyz         1     NONE   float   xyz 
					// COLOR                    0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 0   xy          3     NONE   float   xy  
					// TEXCOORD                 1   xy          4     NONE   float    y  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// COLOR                    1   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        3     NONE   float   xyzw
					// TEXCOORD                 1   xyzw        4     NONE   float   xyzw
					// TEXCOORD                 2   xyzw        5     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[29], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_constantbuffer CB2[7], immediateIndexed
					dcl_constantbuffer CB3[21], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xyz
					dcl_input v2.xyzw
					dcl_input v3.xy
					dcl_input v4.y
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_output o3.xyzw
					dcl_output o4.xyzw
					dcl_output o5.xyzw
					dcl_temps 5
					add r0.xy, v0.xyxx, cb0[23].zwzz
					mul r1.xyzw, r0.yyyy, cb2[1].xyzw
					mad r1.xyzw, cb2[0].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[2].xyzw, v0.zzzz, r1.xyzw
					add r2.xyzw, r1.xyzw, cb2[3].xyzw
					mad r1.xyz, cb2[3].xyzx, v0.wwww, r1.xyzx
					add r1.xyz, -r1.xyzx, cb1[4].xyzx
					mul r3.xyzw, r2.yyyy, cb3[18].xyzw
					mad r3.xyzw, cb3[17].xyzw, r2.xxxx, r3.xyzw
					mad r3.xyzw, cb3[19].xyzw, r2.zzzz, r3.xyzw
					mad r2.xyzw, cb3[20].xyzw, r2.wwww, r3.xyzw
					mov o0.xyzw, r2.xyzw
					mul r3.xyzw, v2.xyzw, cb0[3].xyzw
					mul r3.xyz, r3.wwww, r3.xyzx
					mov o1.xyzw, r3.xyzw
					mul r4.w, v2.w, cb0[5].w
					mul r4.xyz, r4.wwww, cb0[5].xyzx
					add r4.xyzw, -r3.xyzw, r4.xyzw
					dp3 r0.z, r1.xyzx, r1.xyzx
					rsq r0.z, r0.z
					mul r1.xyz, r0.zzzz, r1.xyzx
					dp3 r2.x, v1.xyzx, cb2[4].xyzx
					dp3 r2.y, v1.xyzx, cb2[5].xyzx
					dp3 r2.z, v1.xyzx, cb2[6].xyzx
					dp3 r0.z, r2.xyzx, r2.xyzx
					rsq r0.z, r0.z
					mul r2.xyz, r0.zzzz, r2.xyzx
					dp3 r0.z, r2.xyzx, r1.xyzx
					mul r1.xy, cb1[6].yyyy, cb3[6].xyxx
					mad r1.xy, cb3[5].xyxx, cb1[6].xxxx, r1.xyxx
					mul r1.xy, |r1.xyxx|, cb0[28].yzyy
					div r1.xy, r2.wwww, r1.xyxx
					dp2 r0.w, r1.xyxx, r1.xyxx
					mad r1.xy, cb0[27].xyxx, l(0.250000, 0.250000, 0.000000, 0.000000), r1.xyxx
					div o5.zw, l(0.000000, 0.000000, 0.250000, 0.250000), r1.xxxy
					rsq r0.w, r0.w
					mul r1.x, |v4.y|, cb0[28].x
					mul r0.w, r0.w, r1.x
					mul r1.x, r0.w, l(1.500000)
					add r1.y, -cb0[28].w, l(1.000000)
					mul r1.y, r1.y, |r1.x|
					mad r0.w, r0.w, l(1.500000), -r1.y
					mad r0.z, |r0.z|, r0.w, r1.y
					eq r0.w, cb3[8].w, l(0.000000)
					movc r0.z, r0.w, r0.z, r1.x
					mul r0.w, cb0[4].y, cb0[22].w
					mad r0.w, r0.w, r0.z, l(1.000000)
					div r1.x, r0.z, r0.w
					mul r0.z, cb0[6].x, cb0[22].w
					mul r0.z, r0.z, l(0.500000)
					mul r0.w, r1.x, r0.z
					add r0.w, r0.w, r0.w
					min r0.w, r0.w, l(1.000000)
					sqrt r0.w, r0.w
					mad o2.xyzw, r0.wwww, r4.xyzw, r3.xyzw
					max r2.xyzw, cb0[26].xyzw, l(-20000000000.000000, -20000000000.000000, -20000000000.000000, -20000000000.000000)
					min r2.xyzw, r2.xyzw, l(20000000000.000000, 20000000000.000000, 20000000000.000000, 20000000000.000000)
					add r1.yz, r0.xxyx, -r2.xxyx
					mad r0.xy, r0.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), -r2.xyxx
					add o5.xy, -r2.zwzz, r0.xyxx
					add r0.xy, -r2.xyxx, r2.zwzz
					div o3.zw, r1.yyyz, r0.xxxy
					mov o3.xy, v3.xyxx
					ge r0.x, l(0.000000), v4.y
					and r0.x, r0.x, l(0x3f800000)
					add r0.y, -cb0[22].y, cb0[22].z
					mad r0.x, r0.x, r0.y, cb0[22].y
					mad r0.x, r0.x, l(0.250000), cb0[4].x
					mul r0.x, r0.x, cb0[22].w
					mad r0.x, -r0.x, l(0.500000), l(0.500000)
					mad r1.w, r0.x, r1.x, l(-0.500000)
					mad o4.y, -r0.z, r1.x, r1.w
					mad o4.z, r0.z, r1.x, r1.w
					mov o4.xw, r1.xxxw
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// COLOR                    1   xyzw        2     NONE   float       
					// TEXCOORD                 0   xyzw        3     NONE   float   xyzw
					// TEXCOORD                 1   xyzw        4     NONE   float   x  w
					// TEXCOORD                 2   xyzw        5     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[32], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v1.xyzw
					dcl_input_ps linear v3.xyzw
					dcl_input_ps linear v4.xw
					dcl_output o0.xyzw
					dcl_temps 3
					movc r0.x, cb0[31].x, l(1.000000), l(0)
					sample r1.xyzw, v3.zwzz, t1.xyzw, s0
					add r0.x, r0.x, -r1.w
					add r0.y, -cb0[29].x, l(1.000000)
					mad r0.x, r0.y, cb0[29].y, |r0.x|
					add r0.x, r0.x, -cb0[29].x
					div_sat r0.x, r0.x, cb0[29].y
					sample r1.xyzw, v3.xyxx, t0.xyzw, s1
					mad_sat r0.y, r1.w, v4.x, -v4.w
					mul r1.w, r0.y, v1.w
					mul r2.xyz, r1.wwww, cb0[30].xyzx
					mad r0.yzw, v1.xxyz, r0.yyyy, -r2.xxyz
					mad r1.xyz, r0.xxxx, r0.yzwy, r2.xyzx
					mul o0.xyzw, r0.xxxx, r1.xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "UNITY_UI_ALPHACLIP" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// COLOR                    1   xyzw        2     NONE   float       
					// TEXCOORD                 0   xyzw        3     NONE   float   xyzw
					// TEXCOORD                 1   xyzw        4     NONE   float   x  w
					// TEXCOORD                 2   xyzw        5     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[32], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v1.xyzw
					dcl_input_ps linear v3.xyzw
					dcl_input_ps linear v4.xw
					dcl_output o0.xyzw
					dcl_temps 3
					movc r0.x, cb0[31].x, l(1.000000), l(0)
					sample r1.xyzw, v3.zwzz, t1.xyzw, s0
					add r0.x, r0.x, -r1.w
					add r0.y, -cb0[29].x, l(1.000000)
					mad r0.x, r0.y, cb0[29].y, |r0.x|
					add r0.x, r0.x, -cb0[29].x
					div_sat r0.x, r0.x, cb0[29].y
					sample r1.xyzw, v3.xyxx, t0.xyzw, s1
					mad_sat r0.y, r1.w, v4.x, -v4.w
					mul r1.w, r0.y, v1.w
					mul r2.xyz, r1.wwww, cb0[30].xyzx
					mad r0.z, r1.w, r0.x, l(-0.001000)
					lt r0.z, r0.z, l(0.000000)
					discard_nz r0.z
					mad r0.yzw, v1.xxyz, r0.yyyy, -r2.xxyz
					mad r1.xyz, r0.xxxx, r0.yzwy, r2.xyzx
					mul r0.xyzw, r0.xxxx, r1.xyzw
					mov o0.xyzw, r0.xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "UNITY_UI_CLIP_RECT" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// COLOR                    1   xyzw        2     NONE   float       
					// TEXCOORD                 0   xyzw        3     NONE   float   xyzw
					// TEXCOORD                 1   xyzw        4     NONE   float   x  w
					// TEXCOORD                 2   xyzw        5     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[32], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v1.xyzw
					dcl_input_ps linear v3.xyzw
					dcl_input_ps linear v4.xw
					dcl_input_ps linear v5.xyzw
					dcl_output o0.xyzw
					dcl_temps 4
					movc r0.x, cb0[31].x, l(1.000000), l(0)
					sample r1.xyzw, v3.zwzz, t1.xyzw, s0
					add r0.x, r0.x, -r1.w
					add r0.y, -cb0[29].x, l(1.000000)
					mad r0.x, r0.y, cb0[29].y, |r0.x|
					add r0.x, r0.x, -cb0[29].x
					div_sat r0.x, r0.x, cb0[29].y
					add r0.yz, -cb0[26].xxyx, cb0[26].zzwz
					add r0.yz, r0.yyzy, -|v5.xxyx|
					mul_sat r0.yz, r0.yyzy, v5.zzwz
					mul r0.y, r0.z, r0.y
					sample r1.xyzw, v3.xyxx, t0.xyzw, s1
					mad_sat r0.z, r1.w, v4.x, -v4.w
					mul r1.xyzw, r0.zzzz, v1.xyzw
					mul r2.w, r0.y, r1.w
					mul r3.xyz, r2.wwww, cb0[30].xyzx
					mad r0.yzw, r1.xxyz, r0.yyyy, -r3.xxyz
					mad r2.xyz, r0.xxxx, r0.yzwy, r3.xyzx
					mul o0.xyzw, r0.xxxx, r2.xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "UNITY_UI_CLIP_RECT" "UNITY_UI_ALPHACLIP" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// COLOR                    1   xyzw        2     NONE   float       
					// TEXCOORD                 0   xyzw        3     NONE   float   xyzw
					// TEXCOORD                 1   xyzw        4     NONE   float   x  w
					// TEXCOORD                 2   xyzw        5     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[32], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v1.xyzw
					dcl_input_ps linear v3.xyzw
					dcl_input_ps linear v4.xw
					dcl_input_ps linear v5.xyzw
					dcl_output o0.xyzw
					dcl_temps 4
					movc r0.x, cb0[31].x, l(1.000000), l(0)
					sample r1.xyzw, v3.zwzz, t1.xyzw, s0
					add r0.x, r0.x, -r1.w
					add r0.y, -cb0[29].x, l(1.000000)
					mad r0.x, r0.y, cb0[29].y, |r0.x|
					add r0.x, r0.x, -cb0[29].x
					div_sat r0.x, r0.x, cb0[29].y
					add r0.yz, -cb0[26].xxyx, cb0[26].zzwz
					add r0.yz, r0.yyzy, -|v5.xxyx|
					mul_sat r0.yz, r0.yyzy, v5.zzwz
					mul r0.y, r0.z, r0.y
					sample r1.xyzw, v3.xyxx, t0.xyzw, s1
					mad_sat r0.z, r1.w, v4.x, -v4.w
					mul r1.xyzw, r0.zzzz, v1.xyzw
					mul r2.w, r0.y, r1.w
					mul r3.xyz, r2.wwww, cb0[30].xyzx
					mad r0.z, r2.w, r0.x, l(-0.001000)
					lt r0.z, r0.z, l(0.000000)
					discard_nz r0.z
					mad r0.yzw, r1.xxyz, r0.yyyy, -r3.xxyz
					mad r2.xyz, r0.xxxx, r0.yzwy, r3.xyzx
					mul r0.xyzw, r0.xxxx, r2.xyzw
					mov o0.xyzw, r0.xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
	CustomEditor "TMPro.EditorUtilities.TMP_SDFShaderGUI"
}