Shader "TextMeshPro/Bitmap" {
	Properties {
		_MainTex ("Font Atlas", 2D) = "white" {}
		_FaceTex ("Font Texture", 2D) = "white" {}
		_FaceColor ("Text Color", Vector) = (1,1,1,1)
		_VertexOffsetX ("Vertex OffsetX", Float) = 0
		_VertexOffsetY ("Vertex OffsetY", Float) = 0
		_MaskSoftnessX ("Mask SoftnessX", Float) = 0
		_MaskSoftnessY ("Mask SoftnessY", Float) = 0
		_ClipRect ("Clip Rect", Vector) = (-32767,-32767,32767,32767)
		_StencilComp ("Stencil Comparison", Float) = 8
		_Stencil ("Stencil ID", Float) = 0
		_StencilOp ("Stencil Operation", Float) = 0
		_StencilWriteMask ("Stencil Write Mask", Float) = 255
		_StencilReadMask ("Stencil Read Mask", Float) = 255
		_ColorMask ("Color Mask", Float) = 15
	}
	SubShader {
		Tags { "IGNOREPROJECTOR" = "true" "QUEUE" = "Transparent" "RenderType" = "Transparent" }
		Pass {
			Tags { "IGNOREPROJECTOR" = "true" "QUEUE" = "Transparent" "RenderType" = "Transparent" }
			Blend SrcAlpha OneMinusSrcAlpha, SrcAlpha OneMinusSrcAlpha
			ColorMask 0 -1
			ZWrite Off
			Cull Off
			Stencil {
				ReadMask 0
				WriteMask 0
				Comp Disabled
				Pass Keep
				Fail Keep
				ZFail Keep
			}
			Fog {
				Mode Off
			}
			GpuProgramID 47968
			Program "vp" {
				SubProgram "d3d11 " {
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					// TEXCOORD                 1   xy          3     NONE   float   x   
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					// TEXCOORD                 1     zw        2     NONE   float     zw
					// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[7], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_constantbuffer CB2[4], immediateIndexed
					dcl_constantbuffer CB3[21], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xyzw
					dcl_input v2.xy
					dcl_input v3.x
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xy
					dcl_output o2.zw
					dcl_output o3.xyzw
					dcl_temps 3
					mul r0.x, v0.w, l(0.500000)
					div r0.xy, r0.xxxx, cb1[6].xyxx
					add r0.zw, v0.xxxy, cb0[4].xxxy
					add r0.xy, r0.xyxx, r0.zwzz
					mul r1.xyzw, r0.yyyy, cb2[1].xyzw
					mad r1.xyzw, cb2[0].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[2].xyzw, v0.zzzz, r1.xyzw
					add r1.xyzw, r1.xyzw, cb2[3].xyzw
					mul r2.xyzw, r1.yyyy, cb3[18].xyzw
					mad r2.xyzw, cb3[17].xyzw, r1.xxxx, r2.xyzw
					mad r2.xyzw, cb3[19].xyzw, r1.zzzz, r2.xyzw
					mad r1.xyzw, cb3[20].xyzw, r1.wwww, r2.xyzw
					div r0.zw, r1.xxxy, r1.wwww
					mul r1.xy, cb1[6].xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
					mul r0.zw, r0.zzzw, r1.xxxy
					round_ne r0.zw, r0.zzzw
					div r0.zw, r0.zzzw, r1.xxxy
					mul o0.xy, r1.wwww, r0.zwzz
					mov o0.zw, r1.zzzw
					mul o1.xyzw, v1.xyzw, cb0[3].xyzw
					mul r0.z, v3.x, l(0.000244)
					round_ni r0.z, r0.z
					mad r0.w, -r0.z, l(4096.000000), v3.x
					mul r0.zw, r0.zzzw, cb0[2].xxxy
					mad o2.zw, r0.zzzw, l(0.000000, 0.000000, 0.001953, 0.001953), cb0[2].zzzw
					mov o2.xy, v2.xyxx
					max r2.xyzw, cb0[5].xyzw, l(-20000000000.000000, -20000000000.000000, -20000000000.000000, -20000000000.000000)
					min r2.xyzw, r2.xyzw, l(20000000000.000000, 20000000000.000000, 20000000000.000000, 20000000000.000000)
					mad r0.xy, r0.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), -r2.xyxx
					add o3.xy, -r2.zwzz, r0.xyxx
					mul r0.z, cb1[6].x, cb3[5].x
					mul r0.w, cb1[6].y, cb3[6].y
					div r0.xy, r1.wwww, |r0.zwzz|
					mad r0.xy, cb0[6].xyxx, l(0.250000, 0.250000, 0.000000, 0.000000), r0.xyxx
					div o3.zw, l(0.000000, 0.000000, 0.250000, 0.250000), r0.xxxy
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "UNITY_UI_ALPHACLIP" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					// TEXCOORD                 1   xy          3     NONE   float   x   
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					// TEXCOORD                 1     zw        2     NONE   float     zw
					// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[7], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_constantbuffer CB2[4], immediateIndexed
					dcl_constantbuffer CB3[21], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xyzw
					dcl_input v2.xy
					dcl_input v3.x
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xy
					dcl_output o2.zw
					dcl_output o3.xyzw
					dcl_temps 3
					mul r0.x, v0.w, l(0.500000)
					div r0.xy, r0.xxxx, cb1[6].xyxx
					add r0.zw, v0.xxxy, cb0[4].xxxy
					add r0.xy, r0.xyxx, r0.zwzz
					mul r1.xyzw, r0.yyyy, cb2[1].xyzw
					mad r1.xyzw, cb2[0].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[2].xyzw, v0.zzzz, r1.xyzw
					add r1.xyzw, r1.xyzw, cb2[3].xyzw
					mul r2.xyzw, r1.yyyy, cb3[18].xyzw
					mad r2.xyzw, cb3[17].xyzw, r1.xxxx, r2.xyzw
					mad r2.xyzw, cb3[19].xyzw, r1.zzzz, r2.xyzw
					mad r1.xyzw, cb3[20].xyzw, r1.wwww, r2.xyzw
					div r0.zw, r1.xxxy, r1.wwww
					mul r1.xy, cb1[6].xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
					mul r0.zw, r0.zzzw, r1.xxxy
					round_ne r0.zw, r0.zzzw
					div r0.zw, r0.zzzw, r1.xxxy
					mul o0.xy, r1.wwww, r0.zwzz
					mov o0.zw, r1.zzzw
					mul o1.xyzw, v1.xyzw, cb0[3].xyzw
					mul r0.z, v3.x, l(0.000244)
					round_ni r0.z, r0.z
					mad r0.w, -r0.z, l(4096.000000), v3.x
					mul r0.zw, r0.zzzw, cb0[2].xxxy
					mad o2.zw, r0.zzzw, l(0.000000, 0.000000, 0.001953, 0.001953), cb0[2].zzzw
					mov o2.xy, v2.xyxx
					max r2.xyzw, cb0[5].xyzw, l(-20000000000.000000, -20000000000.000000, -20000000000.000000, -20000000000.000000)
					min r2.xyzw, r2.xyzw, l(20000000000.000000, 20000000000.000000, 20000000000.000000, 20000000000.000000)
					mad r0.xy, r0.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), -r2.xyxx
					add o3.xy, -r2.zwzz, r0.xyxx
					mul r0.z, cb1[6].x, cb3[5].x
					mul r0.w, cb1[6].y, cb3[6].y
					div r0.xy, r1.wwww, |r0.zwzz|
					mad r0.xy, cb0[6].xyxx, l(0.250000, 0.250000, 0.000000, 0.000000), r0.xyxx
					div o3.zw, l(0.000000, 0.000000, 0.250000, 0.250000), r0.xxxy
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "UNITY_UI_CLIP_RECT" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					// TEXCOORD                 1   xy          3     NONE   float   x   
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					// TEXCOORD                 1     zw        2     NONE   float     zw
					// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[7], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_constantbuffer CB2[4], immediateIndexed
					dcl_constantbuffer CB3[21], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xyzw
					dcl_input v2.xy
					dcl_input v3.x
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xy
					dcl_output o2.zw
					dcl_output o3.xyzw
					dcl_temps 3
					mul r0.x, v0.w, l(0.500000)
					div r0.xy, r0.xxxx, cb1[6].xyxx
					add r0.zw, v0.xxxy, cb0[4].xxxy
					add r0.xy, r0.xyxx, r0.zwzz
					mul r1.xyzw, r0.yyyy, cb2[1].xyzw
					mad r1.xyzw, cb2[0].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[2].xyzw, v0.zzzz, r1.xyzw
					add r1.xyzw, r1.xyzw, cb2[3].xyzw
					mul r2.xyzw, r1.yyyy, cb3[18].xyzw
					mad r2.xyzw, cb3[17].xyzw, r1.xxxx, r2.xyzw
					mad r2.xyzw, cb3[19].xyzw, r1.zzzz, r2.xyzw
					mad r1.xyzw, cb3[20].xyzw, r1.wwww, r2.xyzw
					div r0.zw, r1.xxxy, r1.wwww
					mul r1.xy, cb1[6].xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
					mul r0.zw, r0.zzzw, r1.xxxy
					round_ne r0.zw, r0.zzzw
					div r0.zw, r0.zzzw, r1.xxxy
					mul o0.xy, r1.wwww, r0.zwzz
					mov o0.zw, r1.zzzw
					mul o1.xyzw, v1.xyzw, cb0[3].xyzw
					mul r0.z, v3.x, l(0.000244)
					round_ni r0.z, r0.z
					mad r0.w, -r0.z, l(4096.000000), v3.x
					mul r0.zw, r0.zzzw, cb0[2].xxxy
					mad o2.zw, r0.zzzw, l(0.000000, 0.000000, 0.001953, 0.001953), cb0[2].zzzw
					mov o2.xy, v2.xyxx
					max r2.xyzw, cb0[5].xyzw, l(-20000000000.000000, -20000000000.000000, -20000000000.000000, -20000000000.000000)
					min r2.xyzw, r2.xyzw, l(20000000000.000000, 20000000000.000000, 20000000000.000000, 20000000000.000000)
					mad r0.xy, r0.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), -r2.xyxx
					add o3.xy, -r2.zwzz, r0.xyxx
					mul r0.z, cb1[6].x, cb3[5].x
					mul r0.w, cb1[6].y, cb3[6].y
					div r0.xy, r1.wwww, |r0.zwzz|
					mad r0.xy, cb0[6].xyxx, l(0.250000, 0.250000, 0.000000, 0.000000), r0.xyxx
					div o3.zw, l(0.000000, 0.000000, 0.250000, 0.250000), r0.xxxy
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "UNITY_UI_CLIP_RECT" "UNITY_UI_ALPHACLIP" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					// TEXCOORD                 1   xy          3     NONE   float   x   
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					// TEXCOORD                 1     zw        2     NONE   float     zw
					// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[7], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_constantbuffer CB2[4], immediateIndexed
					dcl_constantbuffer CB3[21], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xyzw
					dcl_input v2.xy
					dcl_input v3.x
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xy
					dcl_output o2.zw
					dcl_output o3.xyzw
					dcl_temps 3
					mul r0.x, v0.w, l(0.500000)
					div r0.xy, r0.xxxx, cb1[6].xyxx
					add r0.zw, v0.xxxy, cb0[4].xxxy
					add r0.xy, r0.xyxx, r0.zwzz
					mul r1.xyzw, r0.yyyy, cb2[1].xyzw
					mad r1.xyzw, cb2[0].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[2].xyzw, v0.zzzz, r1.xyzw
					add r1.xyzw, r1.xyzw, cb2[3].xyzw
					mul r2.xyzw, r1.yyyy, cb3[18].xyzw
					mad r2.xyzw, cb3[17].xyzw, r1.xxxx, r2.xyzw
					mad r2.xyzw, cb3[19].xyzw, r1.zzzz, r2.xyzw
					mad r1.xyzw, cb3[20].xyzw, r1.wwww, r2.xyzw
					div r0.zw, r1.xxxy, r1.wwww
					mul r1.xy, cb1[6].xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
					mul r0.zw, r0.zzzw, r1.xxxy
					round_ne r0.zw, r0.zzzw
					div r0.zw, r0.zzzw, r1.xxxy
					mul o0.xy, r1.wwww, r0.zwzz
					mov o0.zw, r1.zzzw
					mul o1.xyzw, v1.xyzw, cb0[3].xyzw
					mul r0.z, v3.x, l(0.000244)
					round_ni r0.z, r0.z
					mad r0.w, -r0.z, l(4096.000000), v3.x
					mul r0.zw, r0.zzzw, cb0[2].xxxy
					mad o2.zw, r0.zzzw, l(0.000000, 0.000000, 0.001953, 0.001953), cb0[2].zzzw
					mov o2.xy, v2.xyxx
					max r2.xyzw, cb0[5].xyzw, l(-20000000000.000000, -20000000000.000000, -20000000000.000000, -20000000000.000000)
					min r2.xyzw, r2.xyzw, l(20000000000.000000, 20000000000.000000, 20000000000.000000, 20000000000.000000)
					mad r0.xy, r0.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), -r2.xyxx
					add o3.xy, -r2.zwzz, r0.xyxx
					mul r0.z, cb1[6].x, cb3[5].x
					mul r0.w, cb1[6].y, cb3[6].y
					div r0.xy, r1.wwww, |r0.zwzz|
					mad r0.xy, cb0[6].xyxx, l(0.250000, 0.250000, 0.000000, 0.000000), r0.xyxx
					div o3.zw, l(0.000000, 0.000000, 0.250000, 0.250000), r0.xxxy
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					// TEXCOORD                 1     zw        2     NONE   float     zw
					// TEXCOORD                 2   xyzw        3     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v1.xyzw
					dcl_input_ps linear v2.xy
					dcl_input_ps linear v2.zw
					dcl_output o0.xyzw
					dcl_temps 1
					sample r0.xyzw, v2.zwzz, t1.xyzw, s1
					mul o0.xyz, r0.xyzx, v1.xyzx
					sample r0.xyzw, v2.xyxx, t0.xyzw, s0
					mul o0.w, r0.w, v1.w
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "UNITY_UI_ALPHACLIP" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					// TEXCOORD                 1     zw        2     NONE   float     zw
					// TEXCOORD                 2   xyzw        3     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v1.xyzw
					dcl_input_ps linear v2.xy
					dcl_input_ps linear v2.zw
					dcl_output o0.xyzw
					dcl_temps 1
					sample r0.xyzw, v2.xyxx, t0.xyzw, s0
					mad r0.x, v1.w, r0.w, l(-0.001000)
					mul r0.y, r0.w, v1.w
					mov o0.w, r0.y
					lt r0.x, r0.x, l(0.000000)
					discard_nz r0.x
					sample r0.xyzw, v2.zwzz, t1.xyzw, s1
					mul o0.xyz, r0.xyzx, v1.xyzx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "UNITY_UI_CLIP_RECT" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					// TEXCOORD                 1     zw        2     NONE   float     zw
					// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[6], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v1.xyzw
					dcl_input_ps linear v2.xy
					dcl_input_ps linear v2.zw
					dcl_input_ps linear v3.xyzw
					dcl_output o0.xyzw
					dcl_temps 3
					add r0.xy, -cb0[5].xyxx, cb0[5].zwzz
					add r0.xy, r0.xyxx, -|v3.xyxx|
					mul_sat r0.xy, r0.xyxx, v3.zwzz
					mul r0.x, r0.y, r0.x
					sample r1.xyzw, v2.zwzz, t1.xyzw, s1
					mul r1.xyz, r1.xyzx, v1.xyzx
					sample r2.xyzw, v2.xyxx, t0.xyzw, s0
					mul r1.w, r2.w, v1.w
					mul o0.xyzw, r0.xxxx, r1.xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "UNITY_UI_CLIP_RECT" "UNITY_UI_ALPHACLIP" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					// TEXCOORD                 1     zw        2     NONE   float     zw
					// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[6], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v1.xyzw
					dcl_input_ps linear v2.xy
					dcl_input_ps linear v2.zw
					dcl_input_ps linear v3.xyzw
					dcl_output o0.xyzw
					dcl_temps 3
					add r0.xy, -cb0[5].xyxx, cb0[5].zwzz
					add r0.xy, r0.xyxx, -|v3.xyxx|
					mul_sat r0.xy, r0.xyxx, v3.zwzz
					mul r0.x, r0.y, r0.x
					sample r1.xyzw, v2.xyxx, t0.xyzw, s0
					mul r1.w, r1.w, v1.w
					mad r0.y, r1.w, r0.x, l(-0.001000)
					lt r0.y, r0.y, l(0.000000)
					discard_nz r0.y
					sample r2.xyzw, v2.zwzz, t1.xyzw, s1
					mul r1.xyz, r2.xyzx, v1.xyzx
					mul r0.xyzw, r0.xxxx, r1.xyzw
					mov o0.xyzw, r0.xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
	CustomEditor "TMPro.EditorUtilities.TMP_BitmapShaderGUI"
}