Shader "Klei/Flow" {
	Properties {
		_PreviousOffsetTex ("Source", 2D) = "white" {}
		_FlowParameters ("Flow Parameters", Vector) = (0,0,0,0)
		_MinFlow ("Min Flow", Vector) = (0,0,0,0)
	}
	SubShader {
		Pass {
			ZTest Always
			ZWrite Off
			Cull Off
			GpuProgramID 14056
			Program "vp" {
				SubProgram "d3d11 " {
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					vs_4_0
					dcl_constantbuffer CB0[14], immediateIndexed
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_temps 1
					add r0.xy, -cb0[13].xyxx, cb0[13].zwzz
					mad r0.xy, v1.xyxx, r0.xyxx, cb0[13].xyxx
					mad o0.xy, r0.xyxx, l(2.000000, -2.000000, 0.000000, 0.000000), l(-1.000000, 1.000000, 0.000000, 0.000000)
					mov o1.xy, r0.xyxx
					mov o0.zw, l(0,0,0,1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[13], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v1.xy
					dcl_output o0.xyzw
					dcl_temps 2
					mad r0.xy, v1.xyxx, cb0[12].zwzz, cb0[12].xyxx
					sample r0.xyzw, r0.xyxx, t0.xyzw, s1
					add r0.xyzw, r0.xyxy, cb0[11].xyzw
					mul r0.xyzw, r0.xyzw, cb0[10].xxxx
					sample r1.xyzw, v1.xyxx, t1.xyzw, s0
					mad o0.xyzw, r1.xyzw, cb0[10].yyzz, r0.xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
}