Shader "Klei/TiledBlock" {
	Properties {
		_MainTex ("Tex0", 2D) = "" {}
		_NormalTex ("Normal", 2D) = "" {}
		_SpecularTex ("Spec", 2D) = "" {}
		_ShineColour ("Specular Colour", Vector) = (1,1,1,1)
		_Frequency ("Specular Frequency", Float) = 1
	}
	SubShader {
		Tags { "IGNOREPROJECTOR" = "true" "PreviewType" = "Plane" "RenderType" = "Transparent" }
		Pass {
			Tags { "IGNOREPROJECTOR" = "true" "PreviewType" = "Plane" "RenderType" = "Transparent" }
			Blend SrcAlpha OneMinusSrcAlpha, SrcAlpha OneMinusSrcAlpha
			ZTest Always
			ZWrite Off
			Cull Off
			Stencil {
				Ref 1
				Comp Always
				Pass Replace
				Fail Keep
				ZFail Keep
			}
			GpuProgramID 62559
			Program "vp" {
				SubProgram "d3d11 " {
					Keywords { "DISABLE_SHINE" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// COLOR                    0   xyzw        2     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 1   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 2   xyz         3     NONE   float   xyz 
					// TEXCOORD                 4   xyzw        4     NONE   float   xyzw
					// TEXCOORD                 5   xy          5     NONE   float   xy  
					//
					vs_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_constantbuffer CB1[6], immediateIndexed
					dcl_constantbuffer CB2[4], immediateIndexed
					dcl_constantbuffer CB3[21], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xy
					dcl_input v2.xyzw
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_output o3.xyz
					dcl_output o4.xyzw
					dcl_output o5.xy
					dcl_temps 3
					mul r0.xyzw, v0.yyyy, cb2[1].xyzw
					mad r0.xyzw, cb2[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb2[2].xyzw, v0.zzzz, r0.xyzw
					add r1.xyzw, r0.xyzw, cb2[3].xyzw
					mad r0.xyz, cb2[3].xyzx, v0.wwww, r0.xyzx
					mul r2.xyzw, r1.yyyy, cb3[18].xyzw
					mad r2.xyzw, cb3[17].xyzw, r1.xxxx, r2.xyzw
					mad r2.xyzw, cb3[19].xyzw, r1.zzzz, r2.xyzw
					mad r1.xyzw, cb3[20].xyzw, r1.wwww, r2.xyzw
					mov o0.xyzw, r1.xyzw
					mul o1.zw, r0.xxxy, cb0[4].zzzw
					mov o3.xyz, r0.xyzx
					mov o1.xy, v1.xyxx
					mov o2.xyzw, v2.xyzw
					mul r0.x, r1.y, cb1[5].x
					mul r0.w, r0.x, l(0.500000)
					mul r0.xz, r1.xxwx, l(0.500000, 0.000000, 0.500000, 0.000000)
					mov o4.zw, r1.zzzw
					add o4.xy, r0.zzzz, r0.xwxx
					mad r0.x, cb1[4].x, l(2.000000), cb1[4].y
					mul r0.x, r0.x, l(0.100000)
					sincos null, o5.x, r0.x
					sincos o5.y, null, r0.x
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "ENABLE_SHINE" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// COLOR                    0   xyzw        2     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 1   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 2   xyz         3     NONE   float   xyz 
					// TEXCOORD                 4   xyzw        4     NONE   float   xyzw
					// TEXCOORD                 5   xy          5     NONE   float   xy  
					//
					vs_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_constantbuffer CB1[6], immediateIndexed
					dcl_constantbuffer CB2[4], immediateIndexed
					dcl_constantbuffer CB3[21], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xy
					dcl_input v2.xyzw
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_output o3.xyz
					dcl_output o4.xyzw
					dcl_output o5.xy
					dcl_temps 3
					mul r0.xyzw, v0.yyyy, cb2[1].xyzw
					mad r0.xyzw, cb2[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb2[2].xyzw, v0.zzzz, r0.xyzw
					add r1.xyzw, r0.xyzw, cb2[3].xyzw
					mad r0.xyz, cb2[3].xyzx, v0.wwww, r0.xyzx
					mul r2.xyzw, r1.yyyy, cb3[18].xyzw
					mad r2.xyzw, cb3[17].xyzw, r1.xxxx, r2.xyzw
					mad r2.xyzw, cb3[19].xyzw, r1.zzzz, r2.xyzw
					mad r1.xyzw, cb3[20].xyzw, r1.wwww, r2.xyzw
					mov o0.xyzw, r1.xyzw
					mul o1.zw, r0.xxxy, cb0[4].zzzw
					mov o3.xyz, r0.xyzx
					mov o1.xy, v1.xyxx
					mov o2.xyzw, v2.xyzw
					mul r0.x, r1.y, cb1[5].x
					mul r0.w, r0.x, l(0.500000)
					mul r0.xz, r1.xxwx, l(0.500000, 0.000000, 0.500000, 0.000000)
					mov o4.zw, r1.zzzw
					add o4.xy, r0.zzzz, r0.xwxx
					mad r0.x, cb1[4].x, l(2.000000), cb1[4].y
					mul r0.x, r0.x, l(0.100000)
					sincos null, o5.x, r0.x
					sincos o5.y, null, r0.x
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					Keywords { "DISABLE_SHINE" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 1   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 2   xyz         3     NONE   float   xy  
					// TEXCOORD                 4   xyzw        4     NONE   float       
					// TEXCOORD                 5   xy          5     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					// SV_Target                1   xyzw        1   TARGET   float   xyzw
					// SV_Target                2   xyzw        2   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[13], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_sampler s2, mode_default
					dcl_sampler s3, mode_default
					dcl_sampler s4, mode_default
					dcl_sampler s5, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_resource_texture2d (float,float,float,float) t2
					dcl_resource_texture2d (float,float,float,float) t3
					dcl_resource_texture2d (float,float,float,float) t4
					dcl_resource_texture2d (float,float,float,float) t5
					dcl_input_ps linear v1.xyzw
					dcl_input_ps linear v2.xyzw
					dcl_input_ps linear v3.xy
					dcl_output o0.xyzw
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_temps 6
					sample r0.xyzw, v1.xyxx, t0.xyzw, s3
					ge r1.x, l(0.200000), r0.w
					discard_nz r1.x
					sample r1.xyzw, v1.zwzz, t1.xyzw, s1
					add r1.x, -r1.x, l(1.000000)
					sample r2.xyzw, v1.zwzz, t2.xyzw, s2
					mul r1.z, r2.x, cb0[7].y
					mul r1.x, r1.x, cb0[12].y
					log r1.x, r1.x
					mul r1.x, r1.x, cb0[12].w
					exp r1.x, r1.x
					add r1.x, r1.x, cb0[12].x
					mad r1.x, r1.z, cb0[12].z, r1.x
					mul r0.xyz, r0.xyzx, r1.xxxx
					mul r2.xyzw, r0.xyzw, v2.xyzw
					mul r1.xz, v3.xxyx, cb0[11].wwww
					sample r3.xyzw, r1.xzxx, t3.xyzw, s5
					mul r0.w, r1.y, r3.w
					mad r0.xyz, -r0.xyzx, v2.xyzx, cb0[11].xyzx
					mad r0.xyz, r0.wwww, r0.xyzx, r2.xyzx
					mul r1.xyz, r0.xyzx, r0.xyzx
					mul r2.xy, v1.zwzz, cb0[4].xyxx
					mul r3.xyzw, r2.yyyy, cb1[1].xyzw
					mad r3.xyzw, cb1[0].xyzw, r2.xxxx, r3.xyzw
					add r3.xyzw, r3.xyzw, cb1[3].xyzw
					mul r2.xy, r3.yyyy, cb2[18].xyxx
					mad r2.xy, cb2[17].xyxx, r3.xxxx, r2.xyxx
					mad r2.xy, cb2[19].xyxx, r3.zzzz, r2.xyxx
					mad r2.xy, cb2[20].xyxx, r3.wwww, r2.xyxx
					mad r2.xy, r2.xyxx, l(0.500000, -0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
					sample r3.xyzw, r2.xyxx, t4.xyzw, s0
					dp3 r0.w, r3.xyzx, l(0.300000, 0.590000, 0.110000, 0.000000)
					mul r1.xyz, r1.xyzx, cb0[10].xyzx
					mad r0.xyz, r0.xyzx, r0.xyzx, -r1.xyzx
					mad r0.xyz, r0.wwww, r0.xyzx, r1.xyzx
					sqrt r0.xyz, r0.xyzx
					add r0.w, -cb0[1].y, l(1.000000)
					sample r1.xyzw, v1.zwzz, t5.xyzw, s4
					min r1.w, r1.y, r1.x
					min r1.w, r1.z, r1.w
					max r2.x, r1.y, r1.x
					max r2.x, r1.z, r2.x
					add r2.y, -r1.w, r2.x
					eq r2.z, r2.y, l(0.000000)
					if_nz r2.z
					  mov r2.z, l(0)
					  mov r3.x, l(0)
					else 
					  add r3.y, r1.w, r2.x
					  lt r3.z, r3.y, l(1.000000)
					  div r3.y, r2.y, r3.y
					  add r1.w, -r1.w, -r2.x
					  add r1.w, r1.w, l(2.000000)
					  div r1.w, r2.y, r1.w
					  movc r3.x, r3.z, r3.y, r1.w
					  add r3.yzw, -r1.yyzx, r2.xxxx
					  mul r1.z, r2.y, l(0.500000)
					  mad r3.yzw, r3.yyzw, l(0.000000, 0.166667, 0.166667, 0.166667), r1.zzzz
					  div r3.yzw, r3.yyzw, r2.yyyy
					  add r1.z, -r3.y, r3.z
					  eq r1.xy, r1.xyxx, r2.xxxx
					  add r2.xy, r3.wyww, l(0.333333, 0.666667, 0.000000, 0.000000)
					  add r2.xy, -r3.zwzz, r2.xyxx
					  movc r1.y, r1.y, r2.x, r2.y
					  movc r1.x, r1.x, r1.z, r1.y
					  lt r1.y, r1.x, l(0.000000)
					  lt r1.z, l(1.000000), r1.x
					  add r2.xy, r1.xxxx, l(1.000000, -1.000000, 0.000000, 0.000000)
					  movc r1.x, r1.z, r2.y, r1.x
					  movc r2.z, r1.y, r2.x, r1.x
					endif 
					min r1.x, r0.y, r0.x
					min r1.x, r0.z, r1.x
					max r1.y, r0.y, r0.x
					max r1.y, r0.z, r1.y
					add r1.x, r1.x, r1.y
					mul r1.yzw, r1.xxxx, l(0.000000, 0.500000, 0.500000, 0.500000)
					eq r2.x, r3.x, l(0.000000)
					if_z r2.x
					  lt r2.x, r1.x, l(1.000000)
					  add r2.y, r3.x, l(1.000000)
					  mul r2.y, r1.w, r2.y
					  mad r3.y, r1.x, l(0.500000), r3.x
					  mad r3.x, -r3.x, r1.w, r3.y
					  movc r2.x, r2.x, r2.y, r3.x
					  add r1.x, r1.x, -r2.x
					  add r3.xyzw, r2.zzzz, l(0.333333, 1.333333, -0.666667, 1.000000)
					  lt r2.y, r3.x, l(0.000000)
					  lt r4.x, l(1.000000), r3.x
					  movc r3.x, r4.x, r3.z, r3.x
					  movc r2.y, r2.y, r3.y, r3.x
					  add r3.x, -r1.x, r2.x
					  mul r3.y, r3.x, l(6.000000)
					  mad r3.z, r3.y, r2.y, r1.x
					  lt r4.xyz, r2.yyyy, l(0.166667, 0.500000, 0.666667, 0.000000)
					  add r2.y, -r2.y, l(0.666667)
					  mul r2.y, r2.y, r3.x
					  mad r2.y, r2.y, l(6.000000), r1.x
					  movc r2.y, r4.z, r2.y, r1.x
					  movc r2.y, r4.y, r2.x, r2.y
					  movc r1.y, r4.x, r3.z, r2.y
					  lt r2.y, r2.z, l(0.000000)
					  lt r3.z, l(1.000000), r2.z
					  add r4.xyzw, r2.zzzz, l(-1.000000, -0.333333, 0.666667, -1.333333)
					  movc r2.z, r3.z, r4.x, r2.z
					  movc r2.y, r2.y, r3.w, r2.z
					  mad r2.z, r3.y, r2.y, r1.x
					  lt r5.xyz, r2.yyyy, l(0.166667, 0.500000, 0.666667, 0.000000)
					  add r2.y, -r2.y, l(0.666667)
					  mul r2.y, r2.y, r3.x
					  mad r2.y, r2.y, l(6.000000), r1.x
					  movc r2.y, r5.z, r2.y, r1.x
					  movc r2.y, r5.y, r2.x, r2.y
					  movc r1.z, r5.x, r2.z, r2.y
					  lt r2.y, r4.y, l(0.000000)
					  lt r2.z, l(1.000000), r4.y
					  movc r2.z, r2.z, r4.w, r4.y
					  movc r2.y, r2.y, r4.z, r2.z
					  mad r2.z, r3.y, r2.y, r1.x
					  lt r3.yzw, r2.yyyy, l(0.000000, 0.166667, 0.500000, 0.666667)
					  add r2.y, -r2.y, l(0.666667)
					  mul r2.y, r2.y, r3.x
					  mad r2.y, r2.y, l(6.000000), r1.x
					  movc r1.x, r3.w, r2.y, r1.x
					  movc r1.x, r3.z, r2.x, r1.x
					  movc r1.w, r3.y, r2.z, r1.x
					endif 
					mul r1.xyz, r1.yzwy, cb0[1].yyyy
					mad o0.xyz, r0.xyzx, r0.wwww, r1.xyzx
					lt r0.x, l(0.500000), r2.w
					and o2.w, r0.x, l(0x3f800000)
					mov o0.w, r2.w
					mov o1.xyz, l(0,0,0,0)
					mov o1.w, r2.w
					mov o2.xyz, cb0[9].xyzx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "ENABLE_SHINE" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 1   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 2   xyz         3     NONE   float   xy  
					// TEXCOORD                 4   xyzw        4     NONE   float   xy  
					// TEXCOORD                 5   xy          5     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					// SV_Target                1   xyzw        1   TARGET   float   xyzw
					// SV_Target                2   xyzw        2   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[17], immediateIndexed
					dcl_constantbuffer CB1[5], immediateIndexed
					dcl_constantbuffer CB2[4], immediateIndexed
					dcl_constantbuffer CB3[21], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_sampler s2, mode_default
					dcl_sampler s3, mode_default
					dcl_sampler s4, mode_default
					dcl_sampler s5, mode_default
					dcl_sampler s6, mode_default
					dcl_sampler s7, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_resource_texture2d (float,float,float,float) t2
					dcl_resource_texture2d (float,float,float,float) t3
					dcl_resource_texture2d (float,float,float,float) t4
					dcl_resource_texture2d (float,float,float,float) t5
					dcl_resource_texture2d (float,float,float,float) t6
					dcl_resource_texture2d (float,float,float,float) t7
					dcl_input_ps linear v1.xyzw
					dcl_input_ps linear v2.xyzw
					dcl_input_ps linear v3.xy
					dcl_input_ps linear v4.xy
					dcl_input_ps linear v5.xy
					dcl_output o0.xyzw
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_temps 6
					sample r0.xyzw, v1.xyxx, t0.xyzw, s3
					ge r1.x, l(0.200000), r0.w
					discard_nz r1.x
					sample r1.xyzw, v1.zwzz, t1.xyzw, s1
					add r1.x, -r1.x, l(1.000000)
					sample r2.xyzw, v1.zwzz, t2.xyzw, s2
					mul r1.z, r2.x, cb0[7].y
					mul r1.x, r1.x, cb0[12].y
					log r1.x, r1.x
					mul r1.x, r1.x, cb0[12].w
					exp r1.x, r1.x
					add r1.x, r1.x, cb0[12].x
					mad r1.x, r1.z, cb0[12].z, r1.x
					mul r0.xyz, r0.xyzx, r1.xxxx
					mul r2.xyzw, r0.xyzw, v2.xyzw
					mul r1.xz, v3.xxyx, cb0[11].wwww
					sample r3.xyzw, r1.xzxx, t3.xyzw, s5
					mul r0.w, r1.y, r3.w
					mad r0.xyz, -r0.xyzx, v2.xyzx, cb0[11].xyzx
					mad r0.xyz, r0.wwww, r0.xyzx, r2.xyzx
					mul r1.xyz, r0.xyzx, r0.xyzx
					mul r2.xy, v1.zwzz, cb0[4].xyxx
					mul r3.xyzw, r2.yyyy, cb2[1].xyzw
					mad r3.xyzw, cb2[0].xyzw, r2.xxxx, r3.xyzw
					add r3.xyzw, r3.xyzw, cb2[3].xyzw
					mul r2.xy, r3.yyyy, cb3[18].xyxx
					mad r2.xy, cb3[17].xyxx, r3.xxxx, r2.xyxx
					mad r2.xy, cb3[19].xyxx, r3.zzzz, r2.xyxx
					mad r2.xy, cb3[20].xyxx, r3.wwww, r2.xyxx
					mad r2.xy, r2.xyxx, l(0.500000, -0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
					sample r3.xyzw, r2.xyxx, t4.xyzw, s0
					dp3 r0.w, r3.xyzx, l(0.300000, 0.590000, 0.110000, 0.000000)
					mul r1.xyz, r1.xyzx, cb0[10].xyzx
					mad r0.xyz, r0.xyzx, r0.xyzx, -r1.xyzx
					mad r0.xyz, r0.wwww, r0.xyzx, r1.xyzx
					sqrt r0.xyz, r0.xyzx
					add r0.w, -cb0[1].y, l(1.000000)
					sample r1.xyzw, v1.zwzz, t5.xyzw, s4
					min r1.w, r1.y, r1.x
					min r1.w, r1.z, r1.w
					max r2.x, r1.y, r1.x
					max r2.x, r1.z, r2.x
					add r2.y, -r1.w, r2.x
					eq r2.z, r2.y, l(0.000000)
					if_nz r2.z
					  mov r2.z, l(0)
					  mov r3.x, l(0)
					else 
					  add r3.y, r1.w, r2.x
					  lt r3.z, r3.y, l(1.000000)
					  div r3.y, r2.y, r3.y
					  add r1.w, -r1.w, -r2.x
					  add r1.w, r1.w, l(2.000000)
					  div r1.w, r2.y, r1.w
					  movc r3.x, r3.z, r3.y, r1.w
					  add r3.yzw, -r1.yyzx, r2.xxxx
					  mul r1.z, r2.y, l(0.500000)
					  mad r3.yzw, r3.yyzw, l(0.000000, 0.166667, 0.166667, 0.166667), r1.zzzz
					  div r3.yzw, r3.yyzw, r2.yyyy
					  add r1.z, -r3.y, r3.z
					  eq r1.xy, r1.xyxx, r2.xxxx
					  add r2.xy, r3.wyww, l(0.333333, 0.666667, 0.000000, 0.000000)
					  add r2.xy, -r3.zwzz, r2.xyxx
					  movc r1.y, r1.y, r2.x, r2.y
					  movc r1.x, r1.x, r1.z, r1.y
					  lt r1.y, r1.x, l(0.000000)
					  lt r1.z, l(1.000000), r1.x
					  add r2.xy, r1.xxxx, l(1.000000, -1.000000, 0.000000, 0.000000)
					  movc r1.x, r1.z, r2.y, r1.x
					  movc r2.z, r1.y, r2.x, r1.x
					endif 
					min r1.x, r0.y, r0.x
					min r1.x, r0.z, r1.x
					max r1.y, r0.y, r0.x
					max r1.y, r0.z, r1.y
					add r1.x, r1.x, r1.y
					mul r1.yzw, r1.xxxx, l(0.000000, 0.500000, 0.500000, 0.500000)
					eq r2.x, r3.x, l(0.000000)
					if_z r2.x
					  lt r2.x, r1.x, l(1.000000)
					  add r2.y, r3.x, l(1.000000)
					  mul r2.y, r1.w, r2.y
					  mad r3.y, r1.x, l(0.500000), r3.x
					  mad r3.x, -r3.x, r1.w, r3.y
					  movc r2.x, r2.x, r2.y, r3.x
					  add r1.x, r1.x, -r2.x
					  add r3.xyzw, r2.zzzz, l(0.333333, 1.333333, -0.666667, 1.000000)
					  lt r2.y, r3.x, l(0.000000)
					  lt r4.x, l(1.000000), r3.x
					  movc r3.x, r4.x, r3.z, r3.x
					  movc r2.y, r2.y, r3.y, r3.x
					  add r3.x, -r1.x, r2.x
					  mul r3.y, r3.x, l(6.000000)
					  mad r3.z, r3.y, r2.y, r1.x
					  lt r4.xyz, r2.yyyy, l(0.166667, 0.500000, 0.666667, 0.000000)
					  add r2.y, -r2.y, l(0.666667)
					  mul r2.y, r2.y, r3.x
					  mad r2.y, r2.y, l(6.000000), r1.x
					  movc r2.y, r4.z, r2.y, r1.x
					  movc r2.y, r4.y, r2.x, r2.y
					  movc r1.y, r4.x, r3.z, r2.y
					  lt r2.y, r2.z, l(0.000000)
					  lt r3.z, l(1.000000), r2.z
					  add r4.xyzw, r2.zzzz, l(-1.000000, -0.333333, 0.666667, -1.333333)
					  movc r2.z, r3.z, r4.x, r2.z
					  movc r2.y, r2.y, r3.w, r2.z
					  mad r2.z, r3.y, r2.y, r1.x
					  lt r5.xyz, r2.yyyy, l(0.166667, 0.500000, 0.666667, 0.000000)
					  add r2.y, -r2.y, l(0.666667)
					  mul r2.y, r2.y, r3.x
					  mad r2.y, r2.y, l(6.000000), r1.x
					  movc r2.y, r5.z, r2.y, r1.x
					  movc r2.y, r5.y, r2.x, r2.y
					  movc r1.z, r5.x, r2.z, r2.y
					  lt r2.y, r4.y, l(0.000000)
					  lt r2.z, l(1.000000), r4.y
					  movc r2.z, r2.z, r4.w, r4.y
					  movc r2.y, r2.y, r4.z, r2.z
					  mad r2.z, r3.y, r2.y, r1.x
					  lt r3.yzw, r2.yyyy, l(0.000000, 0.166667, 0.500000, 0.666667)
					  add r2.y, -r2.y, l(0.666667)
					  mul r2.y, r2.y, r3.x
					  mad r2.y, r2.y, l(6.000000), r1.x
					  movc r1.x, r3.w, r2.y, r1.x
					  movc r1.x, r3.z, r2.x, r1.x
					  movc r1.w, r3.y, r2.z, r1.x
					endif 
					mul r1.xyz, r1.yzwy, cb0[1].yyyy
					mad r0.xyz, r0.xyzx, r0.wwww, r1.xyzx
					mul r1.xy, v3.xyxx, cb0[16].xyxx
					mad r1.zw, cb0[13].wwww, cb0[3].xxxx, cb1[4].xxxy
					mul r1.zw, r1.zzzw, cb0[16].zzzw
					mad r1.xy, r1.xyxx, l(0.153846, 0.153846, 0.000000, 0.000000), r1.zwzz
					sample r1.xyzw, r1.xyxx, t6.xyzw, s7
					mad r1.xy, r1.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
					mul r1.zw, v4.xxxy, cb0[14].xxxx
					sincos r1.zw, null, r1.zzzw
					mad r1.zw, r1.zzzw, l(0.000000, 0.000000, 2.000000, 2.000000), l(0.000000, 0.000000, -1.000000, -1.000000)
					dp2 r2.x, v5.xyxx, r1.zwzz
					mul r3.xy, v5.yxyy, l(-1.000000, 1.000000, 0.000000, 0.000000)
					dp2 r2.y, r3.xyxx, r1.zwzz
					dp2_sat r0.w, r2.xyxx, r1.xyxx
					sample r1.xyzw, v1.xyxx, t7.xyzw, s6
					mul r0.w, r0.w, r1.w
					mul r0.w, r0.w, cb0[15].w
					mad o0.xyz, cb0[15].xyzx, r0.wwww, r0.xyzx
					lt r0.x, l(0.500000), r2.w
					and o2.w, r0.x, l(0x3f800000)
					mov o0.w, r2.w
					mov o1.xyz, l(0,0,0,0)
					mov o1.w, r2.w
					mov o2.xyz, cb0[9].xyzx
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
}