Shader "Klei/AnimationSimple" {
	Properties {
	}
	SubShader {
		Tags { "IGNOREPROJECTOR" = "true" "PreviewType" = "Plane" "QUEUE" = "Transparent+500" "RenderType" = "Transparent" }
		Pass {
			Tags { "IGNOREPROJECTOR" = "true" "PreviewType" = "Plane" "QUEUE" = "Transparent+500" "RenderType" = "Transparent" }
			Blend SrcAlpha OneMinusSrcAlpha, SrcAlpha OneMinusSrcAlpha
			ZWrite Off
			Cull Off
			GpuProgramID 35670
			Program "vp" {
				SubProgram "d3d11 " {
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1   xyzw        2     NONE   float   x   
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					// COLOR                    0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 1   xyz         3     NONE   float   xyz 
					// TEXCOORD                 2   xyzw        4     NONE   float   xyzw
					// TEXCOORD                 3   xyzw        5     NONE   float   xyzw
					// TEXCOORD                 4   xyzw        6     NONE   float   xyzw
					//
					vs_4_0
					dcl_immediateConstantBuffer { { 1.000000, 0, 0, 0},
					                              { 0, 1.000000, 0, 0},
					                              { 0, 0, 1.000000, 0},
					                              { 0, 0, 0, 1.000000} }
					dcl_constantbuffer CB0[16], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_sampler s2, mode_default
					dcl_sampler s3, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_resource_texture2d (float,float,float,float) t2
					dcl_resource_texture2d (float,float,float,float) t3
					dcl_input v1.xy
					dcl_input v2.x
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_output o3.xyz
					dcl_output o4.xyzw
					dcl_output o5.xyzw
					dcl_output o6.xyzw
					dcl_temps 17
					ftoi r0.x, v1.x
					imul null, r0.y, r0.x, l(7)
					itof r0.y, r0.y
					mul r0.zw, cb0[12].xxxy, l(0.000000, 0.000000, 0.500000, 0.500000)
					add r1.x, r0.y, l(0.500000)
					div r1.yz, r1.xxxx, cb0[12].zzwz
					round_ni r2.yz, r1.yyzy
					mad r1.x, -cb0[12].z, r2.y, r1.x
					round_ni r2.x, r1.x
					mad r1.xy, r2.xzxx, cb0[12].xyxx, r0.zwzz
					sample_l r1.xyzw, r1.xyxx, t0.xyzw, s1, l(0.000000)
					lt r1.z, l(0.000000), r1.z
					ftoi r2.xyz, r1.xywx
					ieq r1.y, r1.z, l(-1)
					ieq r0.x, r0.x, r2.y
					and r0.x, r0.x, r1.y
					ige r1.y, r2.x, l(0)
					and r0.x, r0.x, r1.y
					ige r1.y, r2.x, r2.z
					and r0.x, r0.x, r1.y
					if_nz r0.x
					  ftoi r0.x, v1.y
					  round_z r1.x, r1.x
					  add r1.x, r1.x, l(1.000000)
					  mad r1.x, cb0[11].x, l(0.250000), r1.x
					  mul r1.yz, cb0[10].xxyx, l(0.000000, 0.500000, 0.500000, 0.000000)
					  add r1.x, r1.x, l(0.500000)
					  div r2.yz, r1.xxxx, cb0[10].zzwz
					  round_ni r3.yz, r2.yyzy
					  mad r1.x, -cb0[10].z, r3.y, r1.x
					  round_ni r3.x, r1.x
					  mad r1.xw, r3.xxxz, cb0[10].xxxy, r1.yyyz
					  sample_l r3.xyzw, r1.xwxx, t1.xyzw, s0, l(0.000000)
					  ftoi r1.xw, r3.yyyz
					  ilt r2.y, l(0), r1.x
					  ilt r1.x, r0.x, r1.x
					  and r1.x, r1.x, r2.y
					  ieq r1.w, r2.x, r1.w
					  and r1.x, r1.w, r1.x
					  if_nz r1.x
					    ftoi r1.x, r3.x
					    iadd r0.x, r0.x, r1.x
					    mad r1.x, cb0[11].x, l(0.250000), l(0.500000)
					    div r2.xy, r1.xxxx, cb0[10].zwzz
					    round_ni r2.yz, r2.xxyx
					    mad r1.x, -cb0[10].z, r2.y, r1.x
					    round_ni r2.x, r1.x
					    mad r1.xw, r2.xxxz, cb0[10].xxxy, r1.yyyz
					    sample_l r2.xyzw, r1.xwxx, t1.xyzw, s0, l(0.000000)
					    ftoi r1.x, r2.x
					    ishl r1.w, r0.x, l(2)
					    iadd r1.x, r1.w, r1.x
					    itof r1.x, r1.x
					    mad r1.x, cb0[11].x, l(0.250000), r1.x
					    add r1.w, r1.x, l(0.500000)
					    div r2.xy, r1.wwww, cb0[10].zwzz
					    round_ni r2.yz, r2.xxyx
					    mad r1.w, -cb0[10].z, r2.y, r1.w
					    round_ni r2.x, r1.w
					    mad r2.xy, r2.xzxx, cb0[10].xyxx, r1.yzyy
					    sample_l r2.xyzw, r2.xyxx, t1.xyzw, s0, l(0.000000)
					    ftoi r2.xy, r2.xyxx
					    ige r1.w, r2.x, l(0)
					    ieq r0.x, r0.x, r2.y
					    and r0.x, r0.x, r1.w
					    if_nz r0.x
					      ishl r0.x, r2.x, l(2)
					      itof r0.x, r0.x
					      add r2.yz, r0.xxxx, l(0.000000, 0.500000, 1.500000, 0.000000)
					      div r3.xyzw, r2.yyzz, cb0[10].zwzw
					      round_ni r3.xyzw, r3.xzyw
					      mad r2.yz, -cb0[10].zzzz, r3.xxyx, r2.yyzy
					      round_ni r3.xy, r2.yzyy
					      mad r3.xyzw, r3.xzyw, cb0[10].xyxy, r1.yzyz
					      sample_l r4.xyzw, r3.xyxx, t1.xyzw, s0, l(0.000000)
					      ftoi r2.yz, r4.xxyx
					      sample_l r3.xyzw, r3.zwzz, t1.xyzw, s0, l(0.000000)
					      add r1.w, r3.z, l(0.500000)
					      ftoi r1.w, r1.w
					      round_z r2.w, v1.x
					      ge r3.y, l(0.500000), cb0[15].z
					      if_nz r3.y
					        mov r3.zw, l(0,0,0,0)
					        mov r4.xyzw, l(0,0,0,0)
					        mov r5.xyzw, l(0,0,0,0)
					        mov r6.xyzw, l(0,0,0,0)
					        mov r7.xyzw, l(0,0,0,0)
					      endif 
					      if_z r3.y
					        imul null, r3.y, r2.x, l(3)
					        itof r3.y, r3.y
					        mul r8.x, r2.w, cb0[15].y
					        mad r3.y, r8.x, l(3.000000), r3.y
					        mul r8.xy, cb0[14].xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
					        add r9.xyz, r3.yyyy, l(0.500000, 1.500000, 2.500000, 0.000000)
					        div r10.xyzw, r9.xxyy, cb0[14].zwzw
					        round_ni r10.xyzw, r10.xzyw
					        mad r8.zw, -cb0[14].zzzz, r10.xxxy, r9.xxxy
					        round_ni r10.xy, r8.zwzz
					        mad r10.xyzw, r10.xzyw, cb0[14].xyxy, r8.xyxy
					        sample_l r11.xyzw, r10.xyxx, t2.xyzw, s3, l(0.000000)
					        ftoi r7.z, r11.x
					        lt r7.w, l(0.000000), r11.y
					        sample_l r4.xyzw, r10.zwzz, t2.xyzw, s3, l(0.000000)
					        div r8.zw, r9.zzzz, cb0[14].zzzw
					        round_ni r10.yz, r8.zzwz
					        mad r3.y, -cb0[14].z, r10.y, r9.z
					        round_ni r10.x, r3.y
					        mad r8.xy, r10.xzxx, cb0[14].xyxx, r8.xyxx
					        sample_l r6.xyzw, r8.xyxx, t2.xyzw, s3, l(0.000000)
					        mov r3.zw, r4.zzzy
					        mov r5.xy, r4.xwxx
					        mov r5.zw, r6.zzzy
					        mov r7.xy, r6.xwxx
					      endif 
					      ishl r1.w, r1.w, l(1)
					      itof r1.w, r1.w
					      dp2 r2.w, cb0[15].xxxx, r2.wwww
					      add r1.w, r1.w, r2.w
					      round_z r2.w, r1.w
					      mul r8.xy, cb0[13].xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
					      add r2.w, r2.w, l(0.500000)
					      div r8.zw, r2.wwww, cb0[13].zzzw
					      round_ni r9.yz, r8.zzwz
					      mad r2.w, -cb0[13].z, r9.y, r2.w
					      round_ni r9.x, r2.w
					      mad r8.zw, r9.xxxz, cb0[13].xxxy, r8.xxxy
					      sample_l r9.xyzw, r8.zwzz, t3.xyzw, s2, l(0.000000)
					      lt r2.w, l(0.500000), r9.y
					      movc r2.y, r7.w, r7.z, r2.y
					      ige r3.y, r2.y, l(0)
					      and r2.w, r2.w, r3.y
					      ieq r2.x, r2.x, r2.z
					      and r2.x, r2.x, r2.w
					      if_nz r2.x
					        ftoi r1.w, r1.w
					        ftoi r2.x, v2.x
					        add r10.xyzw, r0.yyyy, l(1.500000, 2.500000, 4.500000, 6.500000)
					        div r11.xyzw, r10.xxyy, cb0[12].zwzw
					        round_ni r11.xyzw, r11.xzyw
					        mad r2.zw, -cb0[12].zzzz, r11.xxxy, r10.xxxy
					        round_ni r11.xy, r2.zwzz
					        mad r11.xyzw, r11.xzyw, cb0[12].xyxy, r0.zwzw
					        sample_l r12.xyzw, r11.xyxx, t0.xyzw, s1, l(0.000000)
					        sample_l r11.xyzw, r11.zwzz, t0.zxyw, s1, l(0.000000)
					        div r13.xyzw, r10.zzww, cb0[12].zwzw
					        round_ni r13.xyzw, r13.xzyw
					        mad r2.zw, -cb0[12].zzzz, r13.xxxy, r10.zzzw
					        round_ni r13.xy, r2.zwzz
					        mad r10.xyzw, r13.xzyw, cb0[12].xyxy, r0.zwzw
					        sample_l r13.xyzw, r10.xyxx, t0.xyzw, s1, l(0.000000)
					        sample_l o5.xyzw, r10.zwzz, t0.xyzw, s1, l(0.000000)
					        add r0.yzw, r1.xxxx, l(0.000000, 1.500000, 2.500000, 3.500000)
					        div r10.xyzw, r0.yyzz, cb0[10].zwzw
					        round_ni r10.xyzw, r10.xzyw
					        mad r0.yz, -cb0[10].zzzz, r10.xxyx, r0.yyzy
					        round_ni r10.xy, r0.yzyy
					        mad r10.xyzw, r10.xzyw, cb0[10].xyxy, r1.yzyz
					        sample_l o2.xyzw, r10.xyxx, t1.xyzw, s0, l(0.000000)
					        sample_l r10.xyzw, r10.zwzz, t1.xyzw, s0, l(0.000000)
					        div r0.yz, r0.wwww, cb0[10].zzwz
					        round_ni r14.yz, r0.yyzy
					        mad r0.y, -cb0[10].z, r14.y, r0.w
					        round_ni r14.x, r0.y
					        mad r0.yz, r14.xxzx, cb0[10].xxyx, r1.yyzy
					        sample_l r14.xyzw, r0.yzyy, t1.xzyw, s0, l(0.000000)
					        iadd r0.y, r1.w, l(1)
					        itof r0.y, r0.y
					        add r0.y, r0.y, l(0.500000)
					        div r0.zw, r0.yyyy, cb0[13].zzzw
					        round_ni r15.yz, r0.zzwz
					        mad r0.y, -cb0[13].z, r15.y, r0.y
					        round_ni r15.x, r0.y
					        mad r0.yz, r15.xxzx, cb0[13].xxyx, r8.xxyx
					        sample_l r8.xyzw, r0.yzyy, t3.xyzw, s2, l(0.000000)
					        mov r15.xz, r10.xxyx
					        mov r15.yw, r14.xxxz
					        dp2 r16.x, r12.xyxx, r15.xyxx
					        dp2 r16.y, r12.xyxx, r15.zwzz
					        mov r14.x, r10.z
					        mov r14.z, l(1.000000)
					        dp3 r16.z, r12.xyzx, r14.xyzx
					        mov r11.x, r12.w
					        dp2 r10.x, r11.xyxx, r15.xyxx
					        dp2 r10.y, r11.xyxx, r15.zwzz
					        dp3 r10.z, r11.xyzx, r14.xyzx
					        mul o4.xyzw, r8.xyzw, r13.xyzw
					        if_nz r7.w
					          mul r0.yz, r4.xxyx, icb[r2.x + 0].xxxx
					          mad r0.yz, icb[r2.x + 0].yyyy, r3.zzwz, r0.yyzy
					          mad r0.yz, icb[r2.x + 0].zzzz, r5.xxyx, r0.yyzy
					          mad r0.yz, icb[r2.x + 0].wwww, r4.zzwz, r0.yyzy
					        else 
					          add r0.w, r0.x, l(2.500000)
					          div r1.xw, r0.wwww, cb0[10].zzzw
					          round_ni r4.yz, r1.xxwx
					          mad r0.w, -cb0[10].z, r4.y, r0.w
					          round_ni r4.x, r0.w
					          mad r1.xw, r4.xxxz, cb0[10].xxxy, r1.yyyz
					          sample_l r4.xyzw, r1.xwxx, t1.xyzw, s0, l(0.000000)
					          mul r8.xyzw, r4.xyzy, icb[r2.x + 0].xxyy
					          add r1.xw, r8.xxxy, r8.zzzw
					          mad r1.xw, icb[r2.x + 0].zzzz, r4.xxxw, r1.xxxw
					          mad r0.yz, icb[r2.x + 0].wwww, r4.zzwz, r1.xxwx
					        endif 
					        mul r4.xy, r9.zzzz, r0.yzyy
					        mov r4.z, l(1.000000)
					        dp3 r0.y, r16.xyzx, r4.xyzx
					        dp3 r0.z, r10.xyzx, r4.xyzx
					        mul r4.xyzw, r0.zzzz, cb1[1].xyzw
					        mad r4.xyzw, cb1[0].xyzw, r0.yyyy, r4.xyzw
					        add r4.xyzw, r4.xyzw, cb1[3].xyzw
					        mul r8.xyzw, r4.yyyy, cb2[18].xyzw
					        mad r8.xyzw, cb2[17].xyzw, r4.xxxx, r8.xyzw
					        mad r8.xyzw, cb2[19].xyzw, r4.zzzz, r8.xyzw
					        mad o0.xyzw, cb2[20].xyzw, r4.wwww, r8.xyzw
					        itof o1.z, r2.y
					        round_z o1.w, v2.x
					        if_nz r7.w
					          mul r0.yz, r6.xxyx, icb[r2.x + 0].xxxx
					          mad r0.yz, icb[r2.x + 0].yyyy, r5.zzwz, r0.yyzy
					          mad r0.yz, icb[r2.x + 0].zzzz, r7.xxyx, r0.yyzy
					          mad o1.xy, icb[r2.x + 0].wwww, r6.zwzz, r0.yzyy
					        else 
					          add r0.x, r0.x, l(3.500000)
					          div r0.yz, r0.xxxx, cb0[10].zzwz
					          round_ni r5.yz, r0.yyzy
					          mad r0.x, -cb0[10].z, r5.y, r0.x
					          round_ni r5.x, r0.x
					          mad r0.xy, r5.xzxx, cb0[10].xyxx, r1.yzyy
					          sample_l r0.xyzw, r0.xyxx, t1.xyzw, s0, l(0.000000)
					          mul r1.xyzw, r0.xyzy, icb[r2.x + 0].xxyy
					          add r1.xy, r1.xyxx, r1.zwzz
					          mad r0.xy, icb[r2.x + 0].zzzz, r0.xwxx, r1.xyxx
					          mad o1.xy, icb[r2.x + 0].wwww, r0.zwzz, r0.xyxx
					        endif 
					        mul r0.x, r3.x, l(0.500000)
					        ge r0.y, r0.x, -r0.x
					        frc r0.x, |r0.x|
					        movc r0.x, r0.y, r0.x, -r0.x
					        eq r0.x, r0.x, l(0.500000)
					        and o6.w, r0.x, l(0x3f800000)
					        mov o6.z, l(0)
					      else 
					        mov o0.xyzw, l(-99999.000000,-99999.000000,-99999.000000,0)
					        mov o1.xyzw, l(-99999.000000,-99999.000000,-99999.000000,0)
					        mov o4.xyzw, l(-99999.000000,-99999.000000,-99999.000000,0)
					        mov o5.xyzw, l(-99999.000000,-99999.000000,-99999.000000,0)
					        mov o2.xyzw, l(-99999.000000,-99999.000000,-99999.000000,0)
					        mov r4.xyz, l(-99999.000000,-99999.000000,-99999.000000,0)
					        mov o6.zw, l(0,0,-99999.000000,-99999.000000)
					      endif 
					    else 
					      mov o0.xyzw, l(-99999.000000,-99999.000000,-99999.000000,0)
					      mov o1.xyzw, l(-99999.000000,-99999.000000,-99999.000000,0)
					      mov o4.xyzw, l(-99999.000000,-99999.000000,-99999.000000,0)
					      mov o5.xyzw, l(-99999.000000,-99999.000000,-99999.000000,0)
					      mov o2.xyzw, l(-99999.000000,-99999.000000,-99999.000000,0)
					      mov r4.xyz, l(-99999.000000,-99999.000000,-99999.000000,0)
					      mov o6.zw, l(0,0,-99999.000000,-99999.000000)
					    endif 
					  else 
					    mov o0.xyzw, l(-99999.000000,-99999.000000,-99999.000000,0)
					    mov o1.xyzw, l(-99999.000000,-99999.000000,-99999.000000,0)
					    mov o4.xyzw, l(-99999.000000,-99999.000000,-99999.000000,0)
					    mov o5.xyzw, l(-99999.000000,-99999.000000,-99999.000000,0)
					    mov o2.xyzw, l(-99999.000000,-99999.000000,-99999.000000,0)
					    mov r4.xyz, l(-99999.000000,-99999.000000,-99999.000000,0)
					    mov o6.zw, l(0,0,-99999.000000,-99999.000000)
					  endif 
					else 
					  mov o0.xyzw, l(-99999.000000,-99999.000000,-99999.000000,0)
					  mov o1.xyzw, l(-99999.000000,-99999.000000,-99999.000000,0)
					  mov o4.xyzw, l(-99999.000000,-99999.000000,-99999.000000,0)
					  mov o5.xyzw, l(-99999.000000,-99999.000000,-99999.000000,0)
					  mov o2.xyzw, l(-99999.000000,-99999.000000,-99999.000000,0)
					  mov r4.xyz, l(-99999.000000,-99999.000000,-99999.000000,0)
					  mov o6.zw, l(0,0,-99999.000000,-99999.000000)
					endif 
					mul o6.xy, r4.xyxx, cb0[5].zwzz
					mov o3.xyz, r4.xyzx
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xyz 
					// COLOR                    0   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 1   xyz         3     NONE   float   xy  
					// TEXCOORD                 2   xyzw        4     NONE   float   xyzw
					// TEXCOORD                 3   xyzw        5     NONE   float   xyzw
					// TEXCOORD                 4   xyzw        6     NONE   float   xy w
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					// SV_Target                1   xyzw        1   TARGET   float   xyzw
					// SV_Target                2   xyzw        2   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[18], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_sampler s2, mode_default
					dcl_sampler s3, mode_default
					dcl_sampler s4, mode_default
					dcl_sampler s5, mode_default
					dcl_sampler s6, mode_default
					dcl_sampler s7, mode_default
					dcl_sampler s8, mode_default
					dcl_sampler s9, mode_default
					dcl_sampler s10, mode_default
					dcl_sampler s11, mode_default
					dcl_sampler s12, mode_default
					dcl_sampler s13, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_resource_texture2d (float,float,float,float) t2
					dcl_resource_texture2d (float,float,float,float) t3
					dcl_resource_texture2d (float,float,float,float) t4
					dcl_resource_texture2d (float,float,float,float) t5
					dcl_resource_texture2d (float,float,float,float) t6
					dcl_resource_texture2d (float,float,float,float) t7
					dcl_resource_texture2d (float,float,float,float) t8
					dcl_resource_texture2d (float,float,float,float) t9
					dcl_resource_texture2d (float,float,float,float) t10
					dcl_resource_texture2d (float,float,float,float) t11
					dcl_resource_texture2d (float,float,float,float) t12
					dcl_resource_texture2d (float,float,float,float) t13
					dcl_input_ps linear v1.xyz
					dcl_input_ps linear v2.xyzw
					dcl_input_ps linear v3.xy
					dcl_input_ps linear v4.xyzw
					dcl_input_ps linear v5.xyzw
					dcl_input_ps linear v6.xyw
					dcl_output o0.xyzw
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_temps 6
					lt r0.x, l(0.500000), v5.w
					add r0.yz, v3.xxyx, -v5.xxyx
					dp2 r0.y, r0.yzyy, r0.yzyy
					add r0.y, -r0.y, v5.z
					lt r0.y, r0.y, l(0.000000)
					and r0.x, r0.x, r0.y
					discard_nz r0.x
					lt r0.x, l(0.500000), v1.z
					if_nz r0.x
					  lt r0.x, v1.z, l(1.500000)
					  if_nz r0.x
					    sample r0.xyzw, v1.xyxx, t0.xyzw, s2
					  else 
					    lt r1.x, v1.z, l(2.500000)
					    if_nz r1.x
					      sample r0.xyzw, v1.xyxx, t1.xyzw, s3
					    else 
					      lt r1.x, v1.z, l(3.500000)
					      if_nz r1.x
					        sample r0.xyzw, v1.xyxx, t2.xyzw, s4
					      else 
					        lt r1.x, v1.z, l(4.500000)
					        if_nz r1.x
					          sample r0.xyzw, v1.xyxx, t3.xyzw, s5
					        else 
					          lt r1.x, v1.z, l(5.500000)
					          if_nz r1.x
					            sample r0.xyzw, v1.xyxx, t4.xyzw, s6
					          else 
					            lt r1.x, v1.z, l(6.500000)
					            if_nz r1.x
					              sample r0.xyzw, v1.xyxx, t5.xyzw, s7
					            else 
					              lt r1.x, v1.z, l(7.500000)
					              if_nz r1.x
					                sample r0.xyzw, v1.xyxx, t6.xyzw, s8
					              else 
					                lt r1.x, v1.z, l(8.500000)
					                if_nz r1.x
					                  sample r0.xyzw, v1.xyxx, t7.xyzw, s9
					                else 
					                  lt r1.x, v1.z, l(9.500000)
					                  if_nz r1.x
					                    sample r0.xyzw, v1.xyxx, t8.xyzw, s10
					                  else 
					                    lt r1.x, v1.z, l(10.500000)
					                    if_nz r1.x
					                      sample r0.xyzw, v1.xyxx, t9.xyzw, s11
					                    else 
					                      lt r1.x, v1.z, l(11.500000)
					                      if_nz r1.x
					                        sample r0.xyzw, v1.xyxx, t10.xyzw, s12
					                      else 
					                        mov r0.xyzw, l(1.000000,0,0,1.000000)
					                      endif 
					                    endif 
					                  endif 
					                endif 
					              endif 
					            endif 
					          endif 
					        endif 
					      endif 
					    endif 
					  endif 
					else 
					  sample r0.xyzw, v1.xyxx, t11.xyzw, s1
					endif 
					eq r1.x, v4.w, l(0.000000)
					if_nz r1.x
					  mul r0.xyz, r0.xyzx, v4.xyzx
					else 
					  mul r1.xyz, r0.xyzx, r0.xyzx
					  mul r2.xy, v6.xyxx, cb0[5].xyxx
					  mul r3.xyzw, r2.yyyy, cb1[1].xyzw
					  mad r2.xyzw, cb1[0].xyzw, r2.xxxx, r3.xyzw
					  add r2.xyzw, r2.xyzw, cb1[3].xyzw
					  mul r3.xy, r2.yyyy, cb2[18].xyxx
					  mad r2.xy, cb2[17].xyxx, r2.xxxx, r3.xyxx
					  mad r2.xy, cb2[19].xyxx, r2.zzzz, r2.xyxx
					  mad r2.xy, cb2[20].xyxx, r2.wwww, r2.xyxx
					  mad r2.xy, r2.xyxx, l(0.500000, -0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
					  sample r2.xyzw, r2.xyxx, t12.xyzw, s0
					  dp3 r1.w, r2.xyzx, l(0.300000, 0.590000, 0.110000, 0.000000)
					  mul r1.xyz, r1.xyzx, cb0[17].xyzx
					  mad r2.xyz, r0.xyzx, r0.xyzx, -r1.xyzx
					  mad r1.xyz, r1.wwww, r2.xyzx, r1.xyzx
					  sqrt r1.xyz, r1.xyzx
					  add r1.w, -cb0[1].y, l(1.000000)
					  sample r2.xyzw, v6.xyxx, t13.xyzw, s13
					  min r2.w, r2.y, r2.x
					  min r2.w, r2.z, r2.w
					  max r3.x, r2.y, r2.x
					  max r3.x, r2.z, r3.x
					  add r3.y, -r2.w, r3.x
					  eq r3.z, r3.y, l(0.000000)
					  if_nz r3.z
					    mov r3.zw, l(0,0,0,0)
					  else 
					    add r4.x, r2.w, r3.x
					    lt r4.y, r4.x, l(1.000000)
					    div r4.x, r3.y, r4.x
					    add r2.w, -r2.w, -r3.x
					    add r2.w, r2.w, l(2.000000)
					    div r2.w, r3.y, r2.w
					    movc r3.w, r4.y, r4.x, r2.w
					    add r4.xyz, -r2.yzxy, r3.xxxx
					    mul r2.z, r3.y, l(0.500000)
					    mad r4.xyz, r4.xyzx, l(0.166667, 0.166667, 0.166667, 0.000000), r2.zzzz
					    div r4.xyz, r4.xyzx, r3.yyyy
					    add r2.z, -r4.x, r4.y
					    eq r2.xy, r2.xyxx, r3.xxxx
					    add r3.xy, r4.zxzz, l(0.333333, 0.666667, 0.000000, 0.000000)
					    add r3.xy, -r4.yzyy, r3.xyxx
					    movc r2.y, r2.y, r3.x, r3.y
					    movc r2.x, r2.x, r2.z, r2.y
					    lt r2.y, r2.x, l(0.000000)
					    lt r2.z, l(1.000000), r2.x
					    add r3.xy, r2.xxxx, l(1.000000, -1.000000, 0.000000, 0.000000)
					    movc r2.x, r2.z, r3.y, r2.x
					    movc r3.z, r2.y, r3.x, r2.x
					  endif 
					  min r2.x, r1.y, r1.x
					  min r2.x, r1.z, r2.x
					  max r2.y, r1.y, r1.x
					  max r2.y, r1.z, r2.y
					  add r2.x, r2.x, r2.y
					  mul r2.yzw, r2.xxxx, l(0.000000, 0.500000, 0.500000, 0.500000)
					  eq r3.x, r3.w, l(0.000000)
					  if_z r3.x
					    lt r3.x, r2.x, l(1.000000)
					    add r3.y, r3.w, l(1.000000)
					    mul r3.y, r2.w, r3.y
					    mad r4.x, r2.x, l(0.500000), r3.w
					    mad r3.w, -r3.w, r2.w, r4.x
					    movc r3.x, r3.x, r3.y, r3.w
					    add r2.x, r2.x, -r3.x
					    add r4.xyzw, r3.zzzz, l(0.333333, 1.333333, -0.666667, 1.000000)
					    lt r3.y, r4.x, l(0.000000)
					    lt r3.w, l(1.000000), r4.x
					    movc r3.w, r3.w, r4.z, r4.x
					    movc r3.y, r3.y, r4.y, r3.w
					    add r3.w, -r2.x, r3.x
					    mul r4.x, r3.w, l(6.000000)
					    mad r4.y, r4.x, r3.y, r2.x
					    lt r5.xyz, r3.yyyy, l(0.166667, 0.500000, 0.666667, 0.000000)
					    add r3.y, -r3.y, l(0.666667)
					    mul r3.y, r3.y, r3.w
					    mad r3.y, r3.y, l(6.000000), r2.x
					    movc r3.y, r5.z, r3.y, r2.x
					    movc r3.y, r5.y, r3.x, r3.y
					    movc r2.y, r5.x, r4.y, r3.y
					    lt r3.y, r3.z, l(0.000000)
					    lt r4.y, l(1.000000), r3.z
					    add r5.xyzw, r3.zzzz, l(-1.000000, -0.333333, 0.666667, -1.333333)
					    movc r3.z, r4.y, r5.x, r3.z
					    movc r3.y, r3.y, r4.w, r3.z
					    mad r3.z, r4.x, r3.y, r2.x
					    lt r4.yzw, r3.yyyy, l(0.000000, 0.166667, 0.500000, 0.666667)
					    add r3.y, -r3.y, l(0.666667)
					    mul r3.y, r3.y, r3.w
					    mad r3.y, r3.y, l(6.000000), r2.x
					    movc r3.y, r4.w, r3.y, r2.x
					    movc r3.y, r4.z, r3.x, r3.y
					    movc r2.z, r4.y, r3.z, r3.y
					    lt r3.y, r5.y, l(0.000000)
					    lt r3.z, l(1.000000), r5.y
					    movc r3.z, r3.z, r5.w, r5.y
					    movc r3.y, r3.y, r5.z, r3.z
					    mad r3.z, r4.x, r3.y, r2.x
					    lt r4.xyz, r3.yyyy, l(0.166667, 0.500000, 0.666667, 0.000000)
					    add r3.y, -r3.y, l(0.666667)
					    mul r3.y, r3.y, r3.w
					    mad r3.y, r3.y, l(6.000000), r2.x
					    movc r2.x, r4.z, r3.y, r2.x
					    movc r2.x, r4.y, r3.x, r2.x
					    movc r2.w, r4.x, r3.z, r2.x
					  endif 
					  mad r2.xyz, r2.yzwy, cb0[1].yyyy, r1.wwww
					  mul r0.xyz, r1.xyzx, r2.xyzx
					  mul r0.xyzw, r0.xyzw, v4.xyzw
					endif 
					mul r0.xyzw, r0.xyzw, v2.xyzw
					lt r1.x, l(0.750000), r0.w
					mov r2.xzw, l(0,0,0,1.000000)
					mov r2.y, v6.w
					and o1.xyzw, r1.xxxx, r2.xyzw
					mov o0.xyzw, r0.xyzw
					mov o2.xyzw, l(0,0,0,0)
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
}