Shader "Klei/TiledWall" {
	Properties {
		_MainTex ("Mask Texture", 2D) = "" {}
		_OutlineTex ("Outline Texture", 2D) = "" {}
		_TileTex ("Detail Texture", 2D) = "" {}
		_TintColor ("Tint Color", Vector) = (1,1,1,1)
	}
	SubShader {
		Tags { "IGNOREPROJECTOR" = "true" "PreviewType" = "Plane" "QUEUE" = "Transparent+500" "RenderType" = "Transparent" }
		Pass {
			Tags { "IGNOREPROJECTOR" = "true" "PreviewType" = "Plane" "QUEUE" = "Transparent+500" "RenderType" = "Transparent" }
			Blend SrcAlpha OneMinusSrcAlpha, SrcAlpha OneMinusSrcAlpha
			Cull Off
			GpuProgramID 32542
			Program "vp" {
				SubProgram "d3d11 " {
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// COLOR                    0   xyzw        2     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 1   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 2   xyz         3     NONE   float   xyz 
					//
					vs_4_0
					dcl_constantbuffer CB0[6], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xy
					dcl_input v2.xyzw
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_output o3.xyz
					dcl_temps 3
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r1.xyzw, r0.xyzw, cb1[3].xyzw
					mad r0.xyz, cb1[3].xyzx, v0.wwww, r0.xyzx
					mul r2.xyzw, r1.yyyy, cb2[18].xyzw
					mad r2.xyzw, cb2[17].xyzw, r1.xxxx, r2.xyzw
					mad r2.xyzw, cb2[19].xyzw, r1.zzzz, r2.xyzw
					mad o0.xyzw, cb2[20].xyzw, r1.wwww, r2.xyzw
					mul o1.zw, r0.xxxy, cb0[5].zzzw
					mov o3.xyz, r0.xyzx
					mov o1.xy, v1.xyxx
					mov o2.xyzw, v2.xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 1   xyzw        2     NONE   float   xyzw
					// TEXCOORD                 2   xyz         3     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					// SV_Target                1   xyzw        1   TARGET   float   xyzw
					// SV_Target                2   xyzw        2   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[17], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_sampler s2, mode_default
					dcl_sampler s3, mode_default
					dcl_sampler s4, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_resource_texture2d (float,float,float,float) t2
					dcl_resource_texture2d (float,float,float,float) t3
					dcl_resource_texture2d (float,float,float,float) t4
					dcl_input_ps linear v1.xyzw
					dcl_input_ps linear v2.xyzw
					dcl_output o0.xyzw
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_temps 6
					mul r0.xy, v1.zwzz, cb0[5].xyxx
					mul r0.zw, r0.xxxy, l(0.000000, 0.000000, 0.003906, 0.003906)
					sample r1.xyzw, v1.xyxx, t0.xyzw, s1
					mad r0.zw, r0.zzzw, cb0[9].xxxy, cb0[9].zzzw
					sample r2.xyzw, r0.zwzz, t1.xyzw, s3
					sample r3.xyzw, v1.xyxx, t2.xyzw, s2
					add r0.z, -r3.w, l(1.000000)
					mul r1.xyz, r3.wwww, r3.xyzx
					mad r4.xyz, r2.xyzx, r0.zzzz, r1.xyzx
					mad r0.z, r1.w, r2.w, r3.w
					min r4.w, r0.z, l(1.000000)
					mul r1.xyzw, v2.xyzw, cb0[12].xyzw
					mul r1.xyzw, r1.xyzw, r4.xyzw
					add r0.z, cb0[10].y, cb0[10].x
					mad r1.xyz, r0.zzzz, l(1.500000, 1.500000, 1.500000, 0.000000), r1.xyzx
					mul r2.xyz, r1.xyzx, r1.xyzx
					mul r3.xyzw, r0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, r0.xxxx, r3.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r3.xy, r0.yyyy, cb2[18].xyxx
					mad r0.xy, cb2[17].xyxx, r0.xxxx, r3.xyxx
					mad r0.xy, cb2[19].xyxx, r0.zzzz, r0.xyxx
					mad r0.xy, cb2[20].xyxx, r0.wwww, r0.xyxx
					mad r0.xy, r0.xyxx, l(0.500000, -0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
					sample r0.xyzw, r0.xyxx, t3.xyzw, s0
					dp3 r0.x, r0.xyzx, l(0.300000, 0.590000, 0.110000, 0.000000)
					mul r0.yzw, r2.xxyz, cb0[15].xxyz
					mad r1.xyz, r1.xyzx, r1.xyzx, -r0.yzwy
					mad r0.yzw, r0.xxxx, r1.xxyz, r0.yyzw
					lt r1.xyz, r0.yzwy, l(0.500000, 0.500000, 0.500000, 0.000000)
					add r2.xyz, r0.yzwy, r0.yzwy
					mul r2.xyz, r2.xyzx, cb0[16].xyzx
					add r3.xyz, -r0.yzwy, l(1.000000, 1.000000, 1.000000, 0.000000)
					add r3.xyz, r3.xyzx, r3.xyzx
					add r4.xyz, -cb0[16].xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
					mad r3.xyz, -r3.xyzx, r4.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
					movc r1.xyz, r1.xyzx, r2.xyzx, r3.xyzx
					add r1.xyz, -r0.yzwy, r1.xyzx
					mad r0.xyz, r0.xxxx, r1.xyzx, r0.yzwy
					sqrt r0.xyz, r0.xyzx
					add r0.w, -cb0[1].y, l(1.000000)
					sample r2.xyzw, v1.zwzz, t4.xyzw, s4
					min r1.x, r2.y, r2.x
					min r1.x, r2.z, r1.x
					max r1.y, r2.y, r2.x
					max r1.y, r2.z, r1.y
					add r1.z, -r1.x, r1.y
					eq r2.w, r1.z, l(0.000000)
					if_nz r2.w
					  mov r2.w, l(0)
					  mov r3.x, l(0)
					else 
					  add r3.y, r1.x, r1.y
					  lt r3.z, r3.y, l(1.000000)
					  div r3.y, r1.z, r3.y
					  add r1.x, -r1.y, -r1.x
					  add r1.x, r1.x, l(2.000000)
					  div r1.x, r1.z, r1.x
					  movc r3.x, r3.z, r3.y, r1.x
					  add r3.yzw, -r2.yyzx, r1.yyyy
					  mul r1.x, r1.z, l(0.500000)
					  mad r3.yzw, r3.yyzw, l(0.000000, 0.166667, 0.166667, 0.166667), r1.xxxx
					  div r3.yzw, r3.yyzw, r1.zzzz
					  add r1.x, -r3.y, r3.z
					  eq r1.yz, r1.yyyy, r2.xxyx
					  add r2.xy, r3.wyww, l(0.333333, 0.666667, 0.000000, 0.000000)
					  add r2.xy, -r3.zwzz, r2.xyxx
					  movc r1.z, r1.z, r2.x, r2.y
					  movc r1.x, r1.y, r1.x, r1.z
					  lt r1.y, r1.x, l(0.000000)
					  lt r1.z, l(1.000000), r1.x
					  add r2.xy, r1.xxxx, l(1.000000, -1.000000, 0.000000, 0.000000)
					  movc r1.x, r1.z, r2.y, r1.x
					  movc r2.w, r1.y, r2.x, r1.x
					endif 
					min r1.x, r0.y, r0.x
					min r1.x, r0.z, r1.x
					max r1.y, r0.y, r0.x
					max r1.y, r0.z, r1.y
					add r1.x, r1.x, r1.y
					mul r2.xyz, r1.xxxx, l(0.500000, 0.500000, 0.500000, 0.000000)
					eq r1.y, r3.x, l(0.000000)
					if_z r1.y
					  lt r1.y, r1.x, l(1.000000)
					  add r1.z, r3.x, l(1.000000)
					  mul r1.z, r1.z, r2.z
					  mad r3.y, r1.x, l(0.500000), r3.x
					  mad r3.x, -r3.x, r2.z, r3.y
					  movc r1.y, r1.y, r1.z, r3.x
					  add r1.x, -r1.y, r1.x
					  add r3.xyzw, r2.wwww, l(0.333333, 1.333333, -0.666667, 1.000000)
					  lt r1.z, r3.x, l(0.000000)
					  lt r4.x, l(1.000000), r3.x
					  movc r3.x, r4.x, r3.z, r3.x
					  movc r1.z, r1.z, r3.y, r3.x
					  add r3.x, -r1.x, r1.y
					  mul r3.y, r3.x, l(6.000000)
					  mad r3.z, r3.y, r1.z, r1.x
					  lt r4.xyz, r1.zzzz, l(0.166667, 0.500000, 0.666667, 0.000000)
					  add r1.z, -r1.z, l(0.666667)
					  mul r1.z, r1.z, r3.x
					  mad r1.z, r1.z, l(6.000000), r1.x
					  movc r1.z, r4.z, r1.z, r1.x
					  movc r1.z, r4.y, r1.y, r1.z
					  movc r2.x, r4.x, r3.z, r1.z
					  lt r1.z, r2.w, l(0.000000)
					  lt r3.z, l(1.000000), r2.w
					  add r4.xyzw, r2.wwww, l(-1.000000, -0.333333, 0.666667, -1.333333)
					  movc r2.w, r3.z, r4.x, r2.w
					  movc r1.z, r1.z, r3.w, r2.w
					  mad r2.w, r3.y, r1.z, r1.x
					  lt r5.xyz, r1.zzzz, l(0.166667, 0.500000, 0.666667, 0.000000)
					  add r1.z, -r1.z, l(0.666667)
					  mul r1.z, r1.z, r3.x
					  mad r1.z, r1.z, l(6.000000), r1.x
					  movc r1.z, r5.z, r1.z, r1.x
					  movc r1.z, r5.y, r1.y, r1.z
					  movc r2.y, r5.x, r2.w, r1.z
					  lt r1.z, r4.y, l(0.000000)
					  lt r2.w, l(1.000000), r4.y
					  movc r2.w, r2.w, r4.w, r4.y
					  movc r1.z, r1.z, r4.z, r2.w
					  mad r2.w, r3.y, r1.z, r1.x
					  lt r3.yzw, r1.zzzz, l(0.000000, 0.166667, 0.500000, 0.666667)
					  add r1.z, -r1.z, l(0.666667)
					  mul r1.z, r1.z, r3.x
					  mad r1.z, r1.z, l(6.000000), r1.x
					  movc r1.x, r3.w, r1.z, r1.x
					  movc r1.x, r3.z, r1.y, r1.x
					  movc r2.z, r3.y, r2.w, r1.x
					endif 
					mul r1.xyz, r2.xyzx, cb0[1].yyyy
					mad o0.xyz, r0.xyzx, r0.wwww, r1.xyzx
					lt r0.x, l(0.500000), r1.w
					and o2.w, r0.x, l(0x3f800000)
					mov o0.w, r1.w
					mov o1.xyz, l(0,0,0,0)
					mov o1.w, r1.w
					mov o2.xyz, cb0[11].xyzx
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
}